import type { Recipe } from "./recipes";

/**
 * Recipes scraped from Instagram Saved → Meals collection.
 * Macros and ingredients are per serving when the caption gave batch sizes.
 * Skip list: recipe-download promo, full-day meal plan posts, caption-less soya salads
 * (covered by creamy-soya-paneer-salad).
 */
export const INSTAGRAM_SAVED_MEALS: Recipe[] = [
  // ---------- breakfast ----------
  {
    id: "oats-macaroni",
    name: "Healthy oats macaroni",
    slot: "breakfast",
    diet: "vegetarian",
    allergens: ["dairy", "gluten"],
    calories: 325,
    protein: 25,
    carbs: 28,
    fat: 10,
    minutes: 15,
    note: "Creamy oats + paneer “macaroni.” From your Instagram breakfast series.",
    videoUrl: "https://www.instagram.com/reel/DaUi_34ChKp/",
    steps: [
      "Lightly brush a pan with oil.",
      "Add chopped garlic and sauté about 2 minutes.",
      "Add onion and green chillies; cook 2–3 minutes.",
      "Add tomato and salt; cook until soft.",
      "Add capsicum and sweet corn; cook 4–5 minutes.",
      "Stir in tomato ketchup.",
      "Pour in 1 cup water, add crumbled paneer, and bring to a boil.",
      "Add oats, mix, and cook until the water is absorbed.",
      "Garnish with spring onions and serve hot.",
    ],
    ingredients: [
      { item: "Garlic", qty: 2, unit: "clove", aisle: "produce" },
      { item: "Onion (small)", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Green chillies", qty: 2, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Capsicum (bell pepper)", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Sweet corn", qty: 1, unit: "tbsp", aisle: "frozen" },
      { item: "Tomato ketchup", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "High-protein low-fat paneer", qty: 80, unit: "g", aisle: "dairy" },
      { item: "Rolled oats", qty: 30, unit: "g", aisle: "pantry" },
      { item: "Spring onions", qty: 2, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "hot-honey-feta-egg-bowl",
    name: "Hot honey feta egg cottage cheese bowl",
    slot: "breakfast",
    diet: "vegetarian",
    allergens: ["dairy", "egg", "gluten"],
    calories: 553,
    protein: 31,
    carbs: 45,
    fat: 27,
    minutes: 15,
    note: "Crispy feta eggs over cottage cheese with hot honey. From your Meals saved folder.",
    videoUrl: "https://www.instagram.com/p/DbKww6Gt1ky/",
    steps: [
      "Mix honey with lemon juice and chilli flakes for hot honey.",
      "Fry crumbled feta until it starts to crisp; drizzle half the honey.",
      "Crack eggs on top, season, fry 3–4 minutes, then cover 1–2 minutes.",
      "Spread cottage cheese in a bowl; toast sourdough.",
      "Top with feta eggs, rocket, and avocado; finish with bagel seasoning and remaining honey.",
    ],
    ingredients: [
      { item: "Feta cheese", qty: 30, unit: "g", aisle: "dairy" },
      { item: "Honey", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Eggs", qty: 2, unit: "ea", aisle: "protein" },
      { item: "Cottage cheese", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Avocado", qty: 50, unit: "g", aisle: "produce" },
      { item: "Rocket (arugula)", qty: 1, unit: "handful", aisle: "produce" },
      { item: "Sourdough", qty: 1, unit: "slice", aisle: "bakery" },
      { item: "Everything bagel seasoning", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Lemon", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Chilli flakes", qty: 0.25, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "chorizo-breakfast-burritos",
    name: "Chorizo breakfast burritos",
    slot: "breakfast",
    diet: "omnivore",
    allergens: ["egg", "dairy", "gluten"],
    calories: 450,
    protein: 50,
    carbs: 18,
    fat: 20,
    minutes: 35,
    note: "Meal-prep burritos — freeze wrapped, microwave + toast to reheat. Macros per burrito.",
    videoUrl: "https://www.instagram.com/p/DZAfxL3Os1C/",
    steps: [
      "Cook chorizo chicken sausages; scramble with eggs, garlic salt, and pepper.",
      "Stir in fat-free cheddar and mozzarella until melted.",
      "Mix chipotle mayo: light mayo, minced chipotle, lime, garlic salt, smoked paprika.",
      "Fill low-cal tortillas, wrap, and freeze up to 3 months if meal prepping.",
      "Reheat: wet paper towel, microwave 5–6 minutes, then pan or air-fry to crisp.",
    ],
    ingredients: [
      { item: "Chorizo chicken sausage", qty: 84, unit: "g", aisle: "protein" },
      { item: "Eggs", qty: 2, unit: "ea", aisle: "protein" },
      { item: "Fat-free cheddar", qty: 27, unit: "g", aisle: "dairy" },
      { item: "Fat-free mozzarella", qty: 45, unit: "g", aisle: "dairy" },
      { item: "Low-calorie tortilla", qty: 1, unit: "ea", aisle: "bakery" },
      { item: "Light mayo", qty: 12, unit: "g", aisle: "pantry" },
      { item: "Chipotle peppers in adobo", qty: 3, unit: "g", aisle: "pantry" },
      { item: "Lime", qty: 0.1, unit: "ea", aisle: "produce" },
    ],
  },

  // ---------- lunch ----------
  {
    id: "creamy-soya-paneer-salad",
    name: "Creamy soya paneer salad",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy", "soy", "nuts"],
    calories: 220,
    protein: 21,
    carbs: 13,
    fat: 9,
    minutes: 20,
    note: "High-protein chopped salad with blended paneer-curd dressing. Macros per serving (batch serves 2).",
    videoUrl: "https://www.instagram.com/p/DZxLOzWBZyR/",
    steps: [
      "Boil soya chunks, squeeze dry, and roast until lightly crispy.",
      "Chop onion, carrot, cucumber, and tomato; toss with soya and coriander.",
      "Blend paneer, curd, soaked cashews, soaked red chillies, lemon, salt, and pepper.",
      "Pour dressing over salad and serve fresh.",
    ],
    ingredients: [
      { item: "Onion", qty: 25, unit: "g", aisle: "produce" },
      { item: "Carrot", qty: 25, unit: "g", aisle: "produce" },
      { item: "Cucumber", qty: 50, unit: "g", aisle: "produce" },
      { item: "Tomato", qty: 50, unit: "g", aisle: "produce" },
      { item: "Dry soya chunks", qty: 25, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 40, unit: "g", aisle: "dairy" },
      { item: "Curd (yogurt)", qty: 50, unit: "g", aisle: "dairy" },
      { item: "Cashews", qty: 5, unit: "g", aisle: "pantry" },
      { item: "Dry red chillies", qty: 1, unit: "ea", aisle: "pantry" },
      { item: "Lemon juice", qty: 0.5, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "taco-bowl-jar",
    name: "Chicken taco bowl jar",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 480,
    protein: 42,
    carbs: 38,
    fat: 16,
    minutes: 30,
    note: "Layer dressing, beans, veggies, chicken, cheese, lettuce, and crushed tortilla in a jar.",
    videoUrl: "https://www.instagram.com/p/DXwhQrXO2mh/",
    steps: [
      "Whisk yogurt, sour cream, sriracha, garlic, lemon, and salt for dressing.",
      "Season chicken breast with garlic powder, paprika, salt, and pepper; cook through.",
      "Layer jar: dressing, black beans, cherry tomatoes, red onion, corn, chicken, cheese, lettuce, crushed corn tortilla.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 150, unit: "g", aisle: "protein" },
      { item: "Greek yogurt", qty: 0.25, unit: "cup", aisle: "dairy" },
      { item: "Sour cream", qty: 0.25, unit: "cup", aisle: "dairy" },
      { item: "Sriracha", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Black beans", qty: 0.5, unit: "cup", aisle: "pantry" },
      { item: "Cherry tomatoes", qty: 0.5, unit: "cup", aisle: "produce" },
      { item: "Red onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Corn", qty: 0.33, unit: "cup", aisle: "frozen" },
      { item: "Shredded cheese", qty: 0.25, unit: "cup", aisle: "dairy" },
      { item: "Lettuce", qty: 1, unit: "cup", aisle: "produce" },
      { item: "Corn tortilla", qty: 1, unit: "ea", aisle: "bakery" },
    ],
  },
  {
    id: "cilantro-lime-sweet-potato-taco-bowl",
    name: "Cilantro lime taco bowl with sweet potatoes",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 407,
    protein: 42,
    carbs: 20,
    fat: 17,
    minutes: 30,
    note: "Lean beef, roasted sweet potatoes, creamy avocado-cilantro sauce. ~2 tbsp sauce per serving.",
    videoUrl: "https://www.instagram.com/p/DRDO4wakzy6/",
    steps: [
      "Cube 2 sweet potatoes; roast or air-fry at 400F until golden.",
      "Sauté onion and garlic; add lean ground beef, taco seasoning, and water; cook through.",
      "Blend avocado, light sour cream, Greek yogurt, cilantro, lime, olive oil, garlic, salt, and pepper.",
      "Build bowls with potatoes, beef, sauce, jalapeños, and optional cotija.",
    ],
    ingredients: [
      { item: "Sweet potato", qty: 0.67, unit: "ea", aisle: "produce" },
      { item: "Lean ground beef", qty: 190, unit: "g", aisle: "protein" },
      { item: "Onion", qty: 0.33, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 1, unit: "clove", aisle: "produce" },
      { item: "Taco seasoning", qty: 2, unit: "tsp", aisle: "pantry" },
      { item: "Avocado", qty: 0.33, unit: "ea", aisle: "produce" },
      { item: "Light sour cream", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Greek yogurt", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Cilantro", qty: 2, unit: "tbsp", aisle: "produce" },
      { item: "Lime", qty: 0.67, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "crunchy-chickpea-salad",
    name: "Crunchy chickpea salad",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 360,
    protein: 24,
    carbs: 42,
    fat: 10,
    minutes: 25,
    note: "Air-fried crispy chickpeas over chopped salad with Greek yogurt dressing.",
    videoUrl: "https://www.instagram.com/p/Da0PudAAp5z/",
    steps: [
      "Pat chickpeas dry; toss with oil, paprika, garlic, cumin, oregano, salt, and pepper.",
      "Air-fry at 200C for 12–15 minutes until crispy.",
      "Chop lettuce, cucumber, tomato, onion, and bell pepper; add optional corn.",
      "Mix Greek yogurt dressing; toss salad, top with chickpeas and coriander.",
    ],
    ingredients: [
      { item: "Cooked chickpeas", qty: 1.5, unit: "cup", aisle: "pantry" },
      { item: "Olive oil", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Lettuce", qty: 1, unit: "cup", aisle: "produce" },
      { item: "Cucumber", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Onion", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Bell pepper", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Sweet corn", qty: 2, unit: "tbsp", aisle: "frozen" },
      { item: "Greek yogurt", qty: 4, unit: "tbsp", aisle: "dairy" },
      { item: "Lemon juice", qty: 1, unit: "tsp", aisle: "produce" },
      { item: "Garlic", qty: 1, unit: "clove", aisle: "produce" },
    ],
  },
  {
    id: "honey-chilli-soya-wrap",
    name: "Honey chilli soya wrap",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["soy", "dairy", "gluten"],
    calories: 420,
    protein: 38,
    carbs: 42,
    fat: 10,
    minutes: 20,
    note: "Peri-peri soya, honey-chilli glaze, Greek yogurt dressing, red cabbage in a roti.",
    videoUrl: "https://www.instagram.com/p/Dba1_FTyWFK/",
    steps: [
      "Toss boiled soya with ginger-garlic paste, peri-peri, and salt; pan-fry until golden.",
      "Simmer chilli sauce, soy sauce, honey, and water; coat soya; sprinkle sesame seeds.",
      "Mix Greek yogurt with chilli oil crisps and honey for dressing.",
      "Wrap soya, dressing, and shredded red cabbage in a roti or whole-wheat tortilla.",
    ],
    ingredients: [
      { item: "Dry soya chunks (boiled)", qty: 120, unit: "g", aisle: "pantry" },
      { item: "Ginger-garlic paste", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Peri-peri seasoning", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Chilli sauce", qty: 2, unit: "tsp", aisle: "pantry" },
      { item: "Soy sauce", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Honey", qty: 1.5, unit: "tsp", aisle: "pantry" },
      { item: "Sesame seeds", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "High-protein Greek yogurt", qty: 80, unit: "g", aisle: "dairy" },
      { item: "Chilli oil crisps", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Red cabbage", qty: 0.5, unit: "cup", aisle: "produce" },
      { item: "Whole wheat roti/tortilla", qty: 1, unit: "ea", aisle: "bakery" },
    ],
  },
  {
    id: "rajma-chawal-jar",
    name: "High-protein rajma chawal jar",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 457,
    protein: 44,
    carbs: 54,
    fat: 6,
    minutes: 15,
    note: "Jar lunch: rajma, rice, air-fried paneer, veggies, and spiced Greek yogurt.",
    videoUrl: "https://www.instagram.com/p/DXhCqJOCDbd/",
    steps: [
      "Layer boiled rajma, cooked rice, and air-fried low-fat paneer in a jar.",
      "Add chopped onion, tomato, and cucumber.",
      "Mix Greek yogurt with rajma masala, cumin, chilli flakes, salt, pepper, and lime.",
      "Top with coriander and dig in.",
    ],
    ingredients: [
      { item: "Boiled rajma (kidney beans)", qty: 100, unit: "g", aisle: "pantry" },
      { item: "Cooked rice", qty: 100, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 100, unit: "g", aisle: "dairy" },
      { item: "0% Greek yogurt", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Cucumber", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Rajma masala", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Lime", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Coriander", qty: 2, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "smash-burger-toastie",
    name: "Smash burger toastie",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["dairy", "gluten", "egg"],
    calories: 677,
    protein: 67,
    carbs: 39,
    fat: 27,
    minutes: 20,
    note: "67g protein smash-burger melt on sourdough with pickled shallot-jalapeño sauce.",
    videoUrl: "https://www.instagram.com/p/DZIXGL8t8SJ/",
    steps: [
      "Smash two 70g lean beef patties; season and cook with diced shallot, jalapeño, and garlic.",
      "Mix ketchup, light mayo, mustard, paprika, vinegar, and sweetener for sauce.",
      "Build on sourdough with mozzarella, light cheese slices, and sauce; toast until melted.",
    ],
    ingredients: [
      { item: "Lean ground beef", qty: 140, unit: "g", aisle: "protein" },
      { item: "Sourdough", qty: 2, unit: "slice", aisle: "bakery" },
      { item: "Mozzarella", qty: 25, unit: "g", aisle: "dairy" },
      { item: "Light cheese slices", qty: 2, unit: "ea", aisle: "dairy" },
      { item: "Shallot", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Jalapeño", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 2, unit: "clove", aisle: "produce" },
      { item: "Reduced-sugar ketchup", qty: 20, unit: "g", aisle: "pantry" },
      { item: "Light mayo", qty: 15, unit: "g", aisle: "pantry" },
      { item: "Mustard", qty: 0.5, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "lazy-salmon-sushi-bowl",
    name: "Lazy salmon cream cheese sushi",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["fish", "dairy"],
    calories: 420,
    protein: 28,
    carbs: 48,
    fat: 12,
    minutes: 25,
    note: "Deconstructed sushi — rice, smoked salmon, cream cheese, nori. No rolling required.",
    videoUrl: "https://www.instagram.com/p/DYwXjvvR5pE/",
    steps: [
      "Cook short-grain sushi rice (or microwave sushi rice).",
      "Slice smoked salmon; warm cream cheese slightly if needed.",
      "Assemble rice with salmon, cream cheese, nori strips, spring onion, and sesame seeds.",
      "Serve with cucumber salad or pickled carrot if you want crunch.",
    ],
    ingredients: [
      { item: "Sushi rice (uncooked)", qty: 0.5, unit: "cup", aisle: "pantry" },
      { item: "Smoked salmon", qty: 75, unit: "g", aisle: "protein" },
      { item: "Cream cheese", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Nori sheet", qty: 0.5, unit: "ea", aisle: "pantry" },
      { item: "Spring onion", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Sesame seeds", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },

  // ---------- dinner ----------
  {
    id: "palak-soya",
    name: "Creamy high-protein palak soya",
    slot: "dinner",
    diet: "vegetarian",
    allergens: ["dairy", "soy", "gluten"],
    calories: 190,
    protein: 21,
    carbs: 16,
    fat: 6,
    minutes: 25,
    note: "No cream — paneer blended smooth. Macros are per serving (batch serves 2). Serve with chapati or rice.",
    videoUrl: "https://www.instagram.com/reel/DapJEKcRRJo/",
    steps: [
      "Heat oil; sauté onion, garlic, and green chillies 3–4 minutes.",
      "Add spinach and cook until it releases its water.",
      "Add coriander powder, turmeric, and salt; cook 4–5 minutes.",
      "Boil soya chunks with water, salt, a pinch of sugar, and ginger-garlic paste. Do not squeeze — add chunks and cooking liquid to the pan; cook 3–4 minutes.",
      "Blend paneer, Kashmiri red chilli powder, and water until smooth; stir into the pan.",
      "Mix, cover, and simmer 4–5 minutes.",
      "Serve hot with chapati or rice.",
    ],
    ingredients: [
      { item: "Mustard oil", qty: 0.25, unit: "tbsp", aisle: "pantry" },
      { item: "Onion", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 2, unit: "clove", aisle: "produce" },
      { item: "Green chillies", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Spinach", qty: 1, unit: "cup", aisle: "produce" },
      { item: "Coriander powder", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Turmeric powder", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Dry soya chunks", qty: 25, unit: "g", aisle: "pantry" },
      { item: "Ginger-garlic paste", qty: 0.25, unit: "tbsp", aisle: "pantry" },
      { item: "High-protein low-fat paneer", qty: 25, unit: "g", aisle: "dairy" },
      { item: "Kashmiri red chilli powder", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Chapati", qty: 2, unit: "ea", aisle: "bakery" },
    ],
  },
  {
    id: "mexican-street-corn-chicken",
    name: "Mexican street corn chicken",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 637,
    protein: 57,
    carbs: 55,
    fat: 21,
    minutes: 45,
    note: "Sheet-pan meal prep: seasoned thighs, creamy street corn, coriander-lime rice. Macros per serving of 6.",
    videoUrl: "https://www.instagram.com/p/DZ8C0bJuz8-/",
    steps: [
      "Season chicken thighs with Mexican spices, lime, and olive oil; roast on a sheet pan.",
      "Mix drained corn with red onion, peppers, jalapeño, yogurt, light mayo, feta, cilantro, and Tajín.",
      "Cook basmati rice; fold in coriander, lime, and salt.",
      "Plate rice, chicken, and street corn salad.",
    ],
    ingredients: [
      { item: "Chicken thighs", qty: 217, unit: "g", aisle: "protein" },
      { item: "Olive oil", qty: 5, unit: "g", aisle: "pantry" },
      { item: "Canned sweet corn", qty: 100, unit: "g", aisle: "pantry" },
      { item: "Red onion", qty: 33, unit: "g", aisle: "produce" },
      { item: "Red bell pepper", qty: 25, unit: "g", aisle: "produce" },
      { item: "Jalapeño", qty: 15, unit: "g", aisle: "produce" },
      { item: "Low-fat yogurt", qty: 50, unit: "g", aisle: "dairy" },
      { item: "Light mayo", qty: 17, unit: "g", aisle: "pantry" },
      { item: "Low-fat feta", qty: 15, unit: "g", aisle: "dairy" },
      { item: "Basmati rice (uncooked)", qty: 42, unit: "g", aisle: "pantry" },
      { item: "Cilantro", qty: 2, unit: "tbsp", aisle: "produce" },
      { item: "Lime", qty: 0.25, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "slow-cooker-chicken-taco-bowls",
    name: "Slow cooker chicken taco bowls",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 535,
    protein: 44,
    carbs: 64,
    fat: 10,
    minutes: 20,
    note: "Set-and-forget thighs with enchilada sauce; bone-broth rice and chipotle-lime yogurt. Per serving of 10.",
    videoUrl: "https://www.instagram.com/p/DLNigR4JYM7/",
    steps: [
      "Add chicken thighs, taco seasoning, enchilada sauce, corn, black beans, and salt to slow cooker; cook until shreddable.",
      "Cook jasmine rice in chicken bone broth.",
      "Blend Greek yogurt, lime, chipotle, adobo, honey, oil, milk, salt, and cilantro for sauce.",
      "Bowl rice, taco chicken, and chipotle-lime sauce; garnish with cilantro.",
    ],
    ingredients: [
      { item: "Chicken thighs", qty: 136, unit: "g", aisle: "protein" },
      { item: "Taco seasoning", qty: 0.3, unit: "packet", aisle: "pantry" },
      { item: "Red enchilada sauce", qty: 48, unit: "g", aisle: "pantry" },
      { item: "Fire-roasted corn", qty: 34, unit: "g", aisle: "frozen" },
      { item: "Black beans", qty: 44, unit: "g", aisle: "pantry" },
      { item: "Jasmine rice (uncooked)", qty: 48, unit: "g", aisle: "pantry" },
      { item: "Chicken bone broth", qty: 91, unit: "g", aisle: "pantry" },
      { item: "0% Greek yogurt", qty: 45, unit: "g", aisle: "dairy" },
      { item: "Chipotle peppers", qty: 0.3, unit: "ea", aisle: "pantry" },
      { item: "Lime juice", qty: 1, unit: "tsp", aisle: "produce" },
      { item: "Honey", qty: 0.5, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "cheesy-beef-taco-potato-bowls",
    name: "Cheesy beef taco potato bowls",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 522,
    protein: 54,
    carbs: 42,
    fat: 14,
    minutes: 45,
    note: "Crispy taco potatoes, lean beef, chipotle sauce, and pico. Macros per serving of 4.",
    videoUrl: "https://www.instagram.com/p/DE-pd7HICHV/",
    steps: [
      "Toss cubed potatoes with taco seasoning and oil; roast until crisp.",
      "Brown lean beef with tomato paste and taco seasoning; top with low-fat mozzarella.",
      "Whisk yogurt, light mayo, chipotle paste, hot sauce, and honey for sauce.",
      "Make pico with tomato, onion, peppers, cilantro, lime, and spices; assemble bowls.",
    ],
    ingredients: [
      { item: "Potatoes", qty: 200, unit: "g", aisle: "produce" },
      { item: "Lean ground beef", qty: 200, unit: "g", aisle: "protein" },
      { item: "Tomato paste", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Low-fat mozzarella", qty: 30, unit: "g", aisle: "dairy" },
      { item: "Fat-free yogurt", qty: 25, unit: "g", aisle: "dairy" },
      { item: "Light mayo", qty: 20, unit: "g", aisle: "pantry" },
      { item: "Chipotle chilli paste", qty: 12, unit: "g", aisle: "pantry" },
      { item: "Tomato", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Red onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Bell pepper", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Lime", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Cilantro", qty: 2, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "taco-loaded-potato-bowl",
    name: "Taco loaded potato bowl",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 560,
    protein: 40,
    carbs: 48,
    fat: 22,
    minutes: 40,
    note: "Yukon golds, taco beef, pico, guac, light sour cream, and cheese.",
    videoUrl: "https://www.instagram.com/p/DL8fFENS13b/",
    steps: [
      "Dice potatoes; toss with oil and taco seasoning; bake at 425F ~30–35 minutes.",
      "Brown lean ground beef with taco seasoning.",
      "Mix pico and guacamole; refrigerate until serving.",
      "Build bowls with potatoes, beef, pico, guac, cheese, and light sour cream.",
    ],
    ingredients: [
      { item: "Yukon gold potatoes", qty: 340, unit: "g", aisle: "produce" },
      { item: "Lean ground beef (93/7)", qty: 115, unit: "g", aisle: "protein" },
      { item: "Taco seasoning", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Tomato", qty: 0.5, unit: "cup", aisle: "produce" },
      { item: "Red onion", qty: 0.25, unit: "cup", aisle: "produce" },
      { item: "Jalapeño", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Avocado", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Cilantro", qty: 0.25, unit: "cup", aisle: "produce" },
      { item: "Mexican blend cheese", qty: 0.25, unit: "cup", aisle: "dairy" },
      { item: "Light sour cream", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Lime", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "loaded-taco-potato-bowls",
    name: "High-protein loaded taco potato bowls",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["egg"],
    calories: 470,
    protein: 47,
    carbs: 32,
    fat: 17,
    minutes: 40,
    note: "Crispy seasoned potatoes, extra-lean mince, fresh salsa, sriracha mayo. Per serving of 4.",
    videoUrl: "https://www.instagram.com/p/C3fE70pvfuo/",
    steps: [
      "Season diced potatoes and roast until crisp.",
      "Cook extra-lean beef with tomato paste and taco seasoning; loosen with stock if dry.",
      "Mix tomato, jalapeño, red onion, lime, and cilantro for salsa.",
      "Assemble with sriracha mayo; keep salsa separate for meal prep.",
    ],
    ingredients: [
      { item: "Potatoes", qty: 200, unit: "g", aisle: "produce" },
      { item: "Extra-lean ground beef", qty: 200, unit: "g", aisle: "protein" },
      { item: "Tomato paste", qty: 9, unit: "g", aisle: "pantry" },
      { item: "Tomato", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Jalapeño", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Red onion", qty: 0.125, unit: "ea", aisle: "produce" },
      { item: "Lime", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Cilantro", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Sriracha mayonnaise", qty: 30, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "chicken-65-garlic-bread",
    name: "Chicken 65 garlic bread",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["egg", "dairy", "gluten", "soy"],
    calories: 680,
    protein: 48,
    carbs: 52,
    fat: 28,
    minutes: 50,
    note: "Spicy chicken 65 piled on roasted-garlic mozzarella bread. Shareable — macros estimated per hearty serving.",
    videoUrl: "https://www.instagram.com/p/DbVBq2XuSuX/",
    steps: [
      "Marinate chicken with spices, ginger-garlic, lemon; coat with flours, egg white, baking soda; shallow-fry.",
      "Sauté cumin, garlic, ginger, chillies, curry leaves; add sauces and yogurt for chicken 65 sauce; toss chicken.",
      "Roast a garlic head; mash into butter with herbs and chilli flakes; spread on ciabatta.",
      "Top bread with mozzarella and chicken 65; bake until cheese melts; garnish with onion and lime.",
    ],
    ingredients: [
      { item: "Boneless chicken", qty: 170, unit: "g", aisle: "protein" },
      { item: "Ginger-garlic paste", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Cornflour", qty: 2, unit: "tsp", aisle: "pantry" },
      { item: "All-purpose flour", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Egg white", qty: 0.33, unit: "ea", aisle: "protein" },
      { item: "Plain yogurt", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Red chilli sauce", qty: 2, unit: "tsp", aisle: "pantry" },
      { item: "Soy sauce", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Ciabatta or French bread", qty: 0.33, unit: "loaf", aisle: "bakery" },
      { item: "Butter", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Garlic", qty: 0.33, unit: "head", aisle: "produce" },
      { item: "Mozzarella", qty: 40, unit: "g", aisle: "dairy" },
    ],
  },
  {
    id: "rice-cooker-bibimbap",
    name: "Rice cooker bibimbap",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["soy", "egg"],
    calories: 520,
    protein: 32,
    carbs: 62,
    fat: 14,
    minutes: 35,
    note: "One-pot bibimbap — marinated beef and veggies steam with rice; finish with gochujang and a fried egg.",
    videoUrl: "https://www.instagram.com/p/DbXbiL5Rl54/",
    steps: [
      "Marinate thinly sliced beef with Korean BBQ seasoning, soy sauce, and sesame oil.",
      "Rinse short-grain rice; add to cooker with water and stock powder.",
      "Layer beef, carrot, zucchini, mushrooms, spinach, and bean sprouts on top; cook.",
      "Mix gochujang sauce; serve with fried egg, spring onion, and kimchi.",
    ],
    ingredients: [
      { item: "Beef (thinly sliced)", qty: 250, unit: "g", aisle: "protein" },
      { item: "Short-grain rice (uncooked)", qty: 1, unit: "cup", aisle: "pantry" },
      { item: "Soy sauce", qty: 1.5, unit: "tbsp", aisle: "pantry" },
      { item: "Sesame oil", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Carrot", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Zucchini", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Shiitake mushrooms", qty: 200, unit: "g", aisle: "produce" },
      { item: "Spinach", qty: 1, unit: "handful", aisle: "produce" },
      { item: "Bean sprouts", qty: 1, unit: "handful", aisle: "produce" },
      { item: "Gochujang", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Egg", qty: 1, unit: "ea", aisle: "protein" },
    ],
  },
  {
    id: "crispy-honey-soy-chicken",
    name: "Crispy honey soy chicken",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["soy", "gluten"],
    calories: 567,
    protein: 52,
    carbs: 57,
    fat: 14,
    minutes: 35,
    note: "Air-fried thighs with honey-soy glaze, sticky rice, cucumber salad. Per meal of 4.",
    videoUrl: "https://www.instagram.com/p/DbineIINKwm/",
    steps: [
      "Toss chicken thighs with sesame oil, garlic, ginger, white pepper, baking soda, salt, and soy.",
      "Lightly coat in cornstarch and flour; air-fry at 220C ~15 minutes, flipping halfway.",
      "Simmer sweet chilli, soy, sesame oil, rice vinegar, and honey for glaze; toss chicken.",
      "Serve with sticky rice and quick soy-vinegar cucumber salad.",
    ],
    ingredients: [
      { item: "Chicken thighs", qty: 250, unit: "g", aisle: "protein" },
      { item: "Cornstarch", qty: 12, unit: "g", aisle: "pantry" },
      { item: "Plain flour", qty: 12, unit: "g", aisle: "pantry" },
      { item: "Soy sauce", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Sweet chilli sauce", qty: 25, unit: "g", aisle: "pantry" },
      { item: "Honey", qty: 5, unit: "g", aisle: "pantry" },
      { item: "Rice vinegar", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Cooked sticky rice", qty: 150, unit: "g", aisle: "pantry" },
      { item: "Cucumber", qty: 0.25, unit: "cup", aisle: "produce" },
      { item: "Sesame oil", qty: 0.5, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "korean-popcorn-chicken",
    name: "Crispy Korean popcorn chicken",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["egg", "soy", "gluten"],
    calories: 495,
    protein: 50,
    carbs: 68,
    fat: 3,
    minutes: 35,
    note: "Air-fried popcorn chicken in gochujang glaze over sweet sticky rice. Per meal of 4.",
    videoUrl: "https://www.instagram.com/p/DFS3lHktE5r/",
    steps: [
      "Coat chicken breast pieces in soy, pepper, egg, and cornstarch; air-fry at 200C 10–12 minutes.",
      "Simmer soy, water, ketchup, gochujang, rice vinegar, honey, and brown sweetener into glaze.",
      "Cook sticky rice; season with rice vinegar, sweetener, and salt.",
      "Toss chicken in glaze; serve over rice with green onion and sesame seeds.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 200, unit: "g", aisle: "protein" },
      { item: "Egg", qty: 0.25, unit: "ea", aisle: "protein" },
      { item: "Cornstarch", qty: 10, unit: "g", aisle: "pantry" },
      { item: "Soy sauce", qty: 20, unit: "ml", aisle: "pantry" },
      { item: "Gochujang", qty: 0.75, unit: "tbsp", aisle: "pantry" },
      { item: "Low-cal ketchup", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Honey", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Rice vinegar", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Sticky rice (uncooked)", qty: 50, unit: "g", aisle: "pantry" },
      { item: "Green onion", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Sesame seeds", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "burnt-end-bao",
    name: "Poor man's burnt end bao",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["soy", "gluten", "shellfish"],
    calories: 620,
    protein: 36,
    carbs: 58,
    fat: 26,
    minutes: 90,
    note: "Chuck roast burnt ends with sticky BBQ and scallion chimichurri. Serve in steamed bao.",
    videoUrl: "https://www.instagram.com/p/DbliTdYzis-/",
    steps: [
      "Season chuck roast with salt and pepper; roast or smoke until tender; cube into burnt ends.",
      "Simmer BBQ sauce: shallot, garlic, ginger, ketchup, brown sugar, rice vinegar, honey, oyster sauce, soy, sesame oil.",
      "Toss burnt ends in BBQ sauce until glazed.",
      "Mix scallion chimichurri; stuff bao with burnt ends and chimichurri.",
    ],
    ingredients: [
      { item: "Chuck roast", qty: 225, unit: "g", aisle: "protein" },
      { item: "Shallot", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 1, unit: "clove", aisle: "produce" },
      { item: "Ginger", qty: 0.25, unit: "tbsp", aisle: "produce" },
      { item: "Ketchup", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Brown sugar", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Rice vinegar", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Honey", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Oyster sauce", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Soy sauce", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Scallion greens", qty: 0.25, unit: "cup", aisle: "produce" },
      { item: "Bao buns", qty: 2, unit: "ea", aisle: "bakery" },
    ],
  },
  {
    id: "spicy-tuna-sushi-roll",
    name: "Spicy tuna sushi roll",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["fish"],
    calories: 480,
    protein: 28,
    carbs: 62,
    fat: 12,
    minutes: 40,
    note: "Classic spicy tuna rolls with seasoned sushi rice. Macros estimated for ~2 rolls.",
    videoUrl: "https://www.instagram.com/p/DE7yqOmPZyE/",
    steps: [
      "Cook sushi rice; season with warm rice vinegar, sugar, and salt.",
      "Marinate sushi-grade tuna in sriracha, sesame oil, and green onion.",
      "Roll nori with rice, tuna, and cucumber using a plastic-wrapped bamboo mat.",
      "Top with avocado and sesame seeds; slice and serve.",
    ],
    ingredients: [
      { item: "Sushi rice (uncooked)", qty: 0.75, unit: "cup", aisle: "pantry" },
      { item: "Rice vinegar", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Sugar", qty: 2, unit: "tsp", aisle: "pantry" },
      { item: "Sushi-grade tuna", qty: 115, unit: "g", aisle: "protein" },
      { item: "Sriracha", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Sesame oil", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Nori sheets", qty: 2, unit: "ea", aisle: "pantry" },
      { item: "Cucumber", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Avocado", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Sesame seeds", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "salmon-hand-rolls",
    name: "Salmon hand rolls (temaki)",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["fish", "soy"],
    calories: 450,
    protein: 32,
    carbs: 48,
    fat: 14,
    minutes: 30,
    note: "Cone-style hand rolls — sushi rice, seaweed, avocado, cucumber. Per ~2–3 rolls.",
    videoUrl: "https://www.instagram.com/p/C1m529cpaUR/",
    steps: [
      "Season cooked short-grain rice with rice vinegar, sugar, and salt.",
      "Slice sushi-grade salmon, avocado, and mini cucumbers.",
      "Fill nori cones with rice, fish, and veggies; serve with soy, wasabi, and ginger.",
    ],
    ingredients: [
      { item: "Sushi-grade salmon", qty: 115, unit: "g", aisle: "protein" },
      { item: "Short-grain rice (cooked)", qty: 1, unit: "cup", aisle: "pantry" },
      { item: "Nori sheets", qty: 2.5, unit: "ea", aisle: "pantry" },
      { item: "Avocado", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Mini cucumber", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Soy sauce", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Wasabi", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Pickled ginger", qty: 1, unit: "tbsp", aisle: "pantry" },
    ],
  },
  {
    id: "veg-manchurian",
    name: "High-protein veg Manchurian",
    slot: "dinner",
    diet: "vegan",
    allergens: ["soy", "gluten"],
    calories: 380,
    protein: 38,
    carbs: 42,
    fat: 8,
    minutes: 40,
    note: "~36–39g protein for the whole pan — soy-chunk veg balls in Indo-Chinese sauce. Treat as one big dinner or split.",
    videoUrl: "https://www.instagram.com/p/DZwc2G0BB0U/",
    steps: [
      "Soak soy chunks 15 minutes; drain, squeeze, mince.",
      "Mix with ~500g chopped cabbage/carrot/onion, aminos, soy, garlic, chilli sauce, rice flour, and starch; form balls.",
      "Cook balls in a lightly greased pan until golden.",
      "Sauté garlic, ginger, onion, and capsicum; thicken sauce with aminos, soy, chilli sauce, and starch slurry; toss balls in.",
    ],
    ingredients: [
      { item: "Dry soy chunks", qty: 60, unit: "g", aisle: "pantry" },
      { item: "Cabbage / carrot / onion mix", qty: 500, unit: "g", aisle: "produce" },
      { item: "Coconut aminos", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Dark soy sauce", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Rice flour", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Potato starch", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Garlic", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Capsicum (bell pepper)", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Red chilli sauce", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Spring onion", qty: 2, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "classic-smash-burger",
    name: "Classic smash burger",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "gluten", "egg"],
    calories: 650,
    protein: 38,
    carbs: 42,
    fat: 36,
    minutes: 20,
    note: "Thin smashed patties, American cheese, pickles, and special sauce on brioche.",
    videoUrl: "https://www.instagram.com/p/C7zLbdnplNy/",
    steps: [
      "Form 4oz beef balls; mix mayo-ketchup-mustard sauce with Worcestershire, pickle juice, and spices.",
      "Heat pan until water beads; smash beef under onions; season and flip.",
      "Melt cheese; toast brioche; assemble with pickles and sauce.",
    ],
    ingredients: [
      { item: "Ground beef (80/20)", qty: 115, unit: "g", aisle: "protein" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "American cheese", qty: 1, unit: "slice", aisle: "dairy" },
      { item: "Brioche bun", qty: 1, unit: "ea", aisle: "bakery" },
      { item: "Pickles", qty: 3, unit: "ea", aisle: "pantry" },
      { item: "Mayonnaise", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Ketchup", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Mustard", qty: 0.25, unit: "tsp", aisle: "pantry" },
      { item: "Worcestershire sauce", qty: 0.25, unit: "tsp", aisle: "pantry" },
    ],
  },

  // ---------- lunch (batch 2) ----------
  {
    id: "butter-chicken-salad",
    name: "High-protein butter chicken salad",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 490,
    protein: 62,
    carbs: 22,
    fat: 18,
    minutes: 30,
    note: "Grilled chicken, butter-chicken dressing, green chutney, and sautéed peppers over lettuce.",
    videoUrl: "https://www.instagram.com/p/Da0HX3zyffv/",
    steps: [
      "Marinate chicken with ginger-garlic, salt, pepper, and lemon; grill 6–8 minutes.",
      "Blend tomatoes, garlic, ginger, and chillies; simmer with butter, salt, and kasuri methi.",
      "Blend Greek yogurt, coriander, mint, garlic, chillies, and lemon for green chutney.",
      "Sauté bell pepper; assemble over lettuce and onion with chicken, dressing, and chutney.",
    ],
    ingredients: [
      { item: "Chicken", qty: 200, unit: "g", aisle: "protein" },
      { item: "Ginger-garlic paste", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Lemon", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 2, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 6, unit: "clove", aisle: "produce" },
      { item: "Ginger", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Green chillies", qty: 3, unit: "ea", aisle: "produce" },
      { item: "Butter", qty: 1, unit: "tsp", aisle: "dairy" },
      { item: "Kasuri methi", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Greek yogurt", qty: 80, unit: "g", aisle: "dairy" },
      { item: "Coriander", qty: 1, unit: "handful", aisle: "produce" },
      { item: "Mint", qty: 1, unit: "handful", aisle: "produce" },
      { item: "Bell pepper", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Lettuce", qty: 2, unit: "cup", aisle: "produce" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "lemon-pepper-soya-rice-bowl",
    name: "Lemon pepper soya rice bowl",
    slot: "lunch",
    diet: "vegan",
    allergens: ["soy", "gluten"],
    calories: 318,
    protein: 21,
    carbs: 38,
    fat: 8,
    minutes: 20,
    note: "Crispy soya in a peppery garlic-oats gravy over boiled rice.",
    videoUrl: "https://www.instagram.com/p/DNqY2DlJ52H/",
    steps: [
      "Toss boiled soya with rice/oats flour, salt, and pepper; sauté in olive oil.",
      "Sauté garlic; add oats flour, water, salt, pepper, and chilli flakes into a thick sauce.",
      "Fold in coriander and soya; simmer 2–3 minutes; serve over boiled rice.",
    ],
    ingredients: [
      { item: "Dry soya chunks (boiled)", qty: 60, unit: "g", aisle: "pantry" },
      { item: "Boiled rice", qty: 80, unit: "g", aisle: "pantry" },
      { item: "Garlic", qty: 3, unit: "clove", aisle: "produce" },
      { item: "Oats flour", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Olive oil", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Coriander", qty: 2, unit: "tbsp", aisle: "produce" },
      { item: "Chilli flakes", qty: 0.5, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "soya-curry-leftover-rice",
    name: "High-protein soya curry with leftover rice",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["soy", "dairy", "nuts"],
    calories: 380,
    protein: 20,
    carbs: 48,
    fat: 10,
    minutes: 25,
    note: "Cashew-curd soya curry over a katori of leftover rice — ~20g protein.",
    videoUrl: "https://www.instagram.com/p/DLppKKGTsGE/",
    steps: [
      "Blend sautéed onion, cashews, dry red chilli, curd, and green chilli into a puree.",
      "Sauté jeera, onion, and tomato in mustard oil; add puree and masalas.",
      "Add boiled soya; simmer; garnish with coriander; serve with leftover rice.",
    ],
    ingredients: [
      { item: "Cooked rice", qty: 1, unit: "katori", aisle: "pantry" },
      { item: "Dry soya chunks (soaked)", qty: 60, unit: "g", aisle: "pantry" },
      { item: "Tomato", qty: 50, unit: "g", aisle: "produce" },
      { item: "Onion", qty: 20, unit: "g", aisle: "produce" },
      { item: "Cashews", qty: 4, unit: "ea", aisle: "pantry" },
      { item: "Dry red chillies", qty: 2, unit: "ea", aisle: "pantry" },
      { item: "Curd (yogurt)", qty: 15, unit: "g", aisle: "dairy" },
      { item: "Green chilli", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Mustard oil", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Coriander", qty: 2, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "creamy-soya-paneer-rice-bowl",
    name: "Creamy soya rice bowl",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["soy", "dairy", "nuts"],
    calories: 437,
    protein: 28,
    carbs: 49,
    fat: 15,
    minutes: 25,
    note: "Soya in a cashew-paneer cream sauce with veggies over rice. No cream, no maida.",
    videoUrl: "https://www.instagram.com/p/DYta1Miz2yK/",
    steps: [
      "Boil soya chunks; blend paneer, cashews, tomato, curd, and spices into a sauce.",
      "Sauté garlic and mixed veggies; add soya and creamy sauce; optional Schezwan.",
      "Serve over a bowl of cooked rice with coriander.",
    ],
    ingredients: [
      { item: "Dry soya chunks (boiled)", qty: 50, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 40, unit: "g", aisle: "dairy" },
      { item: "Cashews (soaked)", qty: 4, unit: "ea", aisle: "pantry" },
      { item: "Tomato", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Red bell pepper", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Mixed veggies", qty: 1, unit: "cup", aisle: "produce" },
      { item: "Curd (yogurt)", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Cooked rice", qty: 1, unit: "bowl", aisle: "pantry" },
      { item: "Oil or ghee", qty: 1.5, unit: "tsp", aisle: "pantry" },
      { item: "Schezwan sauce", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "soya-paneer-pulao-bowl",
    name: "Soya paneer rice bowl with raita",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["soy", "dairy"],
    calories: 500,
    protein: 44,
    carbs: 52,
    fat: 12,
    minutes: 30,
    note: "Whole-spice soya-paneer pulao with veggie mix and spiced curd raita.",
    videoUrl: "https://www.instagram.com/p/DWDsWSUgZz_/",
    steps: [
      "Temper ghee with jeera and whole spices; sauté garlic, onion, and green chilli.",
      "Add carrot, beans, and peas; then boiled soya and paneer; season.",
      "Remove whole spices; toss with cooked rice; serve with coriander and raita.",
    ],
    ingredients: [
      { item: "Ghee", qty: 1, unit: "tsp", aisle: "dairy" },
      { item: "Dry soya chunks (raw)", qty: 35, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 70, unit: "g", aisle: "dairy" },
      { item: "Onion", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 4, unit: "clove", aisle: "produce" },
      { item: "Carrot", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Green beans", qty: 0.5, unit: "cup", aisle: "produce" },
      { item: "Peas", qty: 0.5, unit: "cup", aisle: "frozen" },
      { item: "Cooked rice", qty: 80, unit: "g", aisle: "pantry" },
      { item: "Curd (yogurt)", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Green chillies", qty: 2, unit: "ea", aisle: "produce" },
      { item: "Coriander", qty: 1, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "creamy-soya-herb-rice-bowl",
    name: "Creamy soya herb rice bowl",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["soy", "dairy", "nuts"],
    calories: 450,
    protein: 35,
    carbs: 48,
    fat: 14,
    minutes: 30,
    note: "Cashew-paneer gravy with soya and sprouts over garlic herb rice. Batch serves 2–3.",
    videoUrl: "https://www.instagram.com/p/DZCHTyooon1/",
    steps: [
      "Sauté tomato, red pepper, cashews, sesame, and paneer; blend with curd and cheese.",
      "Sauté garlic, peppers, soya, and sprouts; pour in sauce; cook 2–3 minutes.",
      "Toss cooked rice with garlic butter, herbs, and chilli flakes; plate together.",
    ],
    ingredients: [
      { item: "Tomato", qty: 0.4, unit: "ea", aisle: "produce" },
      { item: "Red bell pepper", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Cashews (soaked)", qty: 2, unit: "ea", aisle: "pantry" },
      { item: "Sesame seeds", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Paneer", qty: 40, unit: "g", aisle: "dairy" },
      { item: "Curd (yogurt)", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Dry soya chunks", qty: 40, unit: "g", aisle: "pantry" },
      { item: "Steamed sprouts", qty: 0.25, unit: "cup", aisle: "produce" },
      { item: "Cooked rice", qty: 0.5, unit: "cup", aisle: "pantry" },
      { item: "Butter or oil", qty: 0.5, unit: "tsp", aisle: "dairy" },
      { item: "Garlic", qty: 2, unit: "clove", aisle: "produce" },
    ],
  },
  {
    id: "chicken-protein-tortilla-tacos",
    name: "High-protein chicken tortilla tacos",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["egg", "dairy"],
    calories: 520,
    protein: 50,
    carbs: 12,
    fat: 28,
    minutes: 35,
    note: "Blended chicken-Parmesan “tortillas” baked crisp; fill with fajitas or salsa. ~50g protein.",
    videoUrl: "https://www.instagram.com/p/DV3mbgMjGAc/",
    steps: [
      "Blend chicken, egg, Greek yogurt, Parmesan, oil, salt, paprika, and garlic until smooth.",
      "Form thin tortillas; bake at 400F for 25 minutes; top with cheese and flip 5 minutes more.",
      "Fill with fajita veggies or salsa and serve.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 150, unit: "g", aisle: "protein" },
      { item: "Egg", qty: 0.33, unit: "ea", aisle: "protein" },
      { item: "Greek yogurt", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Parmesan", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Olive oil", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Smoked paprika", qty: 0.33, unit: "tsp", aisle: "pantry" },
      { item: "Garlic", qty: 0.33, unit: "clove", aisle: "produce" },
    ],
  },
  {
    id: "taco-chicken-lettuce-boats",
    name: "Sheet-pan taco chicken lettuce boats",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 480,
    protein: 42,
    carbs: 28,
    fat: 22,
    minutes: 35,
    note: "Crispy taco thighs and chili-lime street corn in lettuce boats with cold toppings.",
    videoUrl: "https://www.instagram.com/p/DY29KG8ND9Y/",
    steps: [
      "Toss chopped chicken thighs with taco seasoning, garlic, paprika, and lime; roast at 425F 10 minutes.",
      "Add corn and purple onion with oil and chili powder; roast 10 minutes more, broil 3 minutes.",
      "Finish corn with lime, queso fresco, and cilantro; build lettuce boats with avocado, pico, and crema.",
    ],
    ingredients: [
      { item: "Chicken thighs", qty: 280, unit: "g", aisle: "protein" },
      { item: "Taco seasoning", qty: 0.5, unit: "packet", aisle: "pantry" },
      { item: "Corn kernels", qty: 1, unit: "ear", aisle: "produce" },
      { item: "Purple onion", qty: 0.15, unit: "ea", aisle: "produce" },
      { item: "Queso fresco", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Green leaf lettuce", qty: 4, unit: "leaf", aisle: "produce" },
      { item: "Avocado", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Pico de gallo", qty: 0.25, unit: "cup", aisle: "produce" },
      { item: "Greek yogurt or crema", qty: 2, unit: "tbsp", aisle: "dairy" },
      { item: "Lime", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },

  // ---------- dinner (batch 2) ----------
  {
    id: "rice-cooker-gyudon",
    name: "Rice cooker Japanese gyudon",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["soy", "egg", "fish"],
    calories: 528,
    protein: 47,
    carbs: 59,
    fat: 10,
    minutes: 35,
    note: "One-pot beef and rice with jammy egg. Macros per serving of 2.",
    videoUrl: "https://www.instagram.com/p/DXV_DCsD9-U/",
    steps: [
      "Add rinsed jasmine rice, thinly sliced beef, bone broth, soy, mirin, dashi, onion, and ginger to rice cooker; cook ~30 minutes.",
      "Boil eggs 6 minutes; ice bath for jammy yolks.",
      "Serve half the gyudon with one egg and green onion.",
    ],
    ingredients: [
      { item: "Eye of round beef (thin)", qty: 140, unit: "g", aisle: "protein" },
      { item: "Jasmine rice (uncooked)", qty: 0.33, unit: "cup", aisle: "pantry" },
      { item: "Beef bone broth", qty: 2.5, unit: "tbsp", aisle: "pantry" },
      { item: "Soy sauce", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Mirin", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Dashi powder", qty: 0.25, unit: "tsp", aisle: "pantry" },
      { item: "Yellow onion", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Ginger", qty: 0.25, unit: "tbsp", aisle: "produce" },
      { item: "Egg", qty: 1, unit: "ea", aisle: "protein" },
      { item: "Green onion", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "green-butter-garlic-chicken",
    name: "Green butter garlic chicken",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["soy", "dairy", "gluten"],
    calories: 480,
    protein: 58,
    carbs: 19,
    fat: 16,
    minutes: 35,
    note: "Crispy chicken in coriander-paneer butter-garlic sauce. Macros per serving of 2.",
    videoUrl: "https://www.instagram.com/p/DbM-fAjJRRB/",
    steps: [
      "Marinate chicken cubes with cornflour, baking soda, salt, pepper, and soy 15–20 minutes.",
      "Blend soaked paneer with coriander and green chillies.",
      "Pan-fry chicken until crisp; set aside.",
      "Cook light butter, garlic, and onion; stir in paneer puree, spices, and stock cube; toss chicken; finish with lemon.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 200, unit: "g", aisle: "protein" },
      { item: "Cornflour", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Soy sauce", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "High-protein paneer", qty: 50, unit: "g", aisle: "dairy" },
      { item: "Coriander", qty: 1, unit: "handful", aisle: "produce" },
      { item: "Green chillies", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Light butter", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Garlic", qty: 5, unit: "clove", aisle: "produce" },
      { item: "Onion (small)", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Lemon juice", qty: 0.25, unit: "tsp", aisle: "produce" },
    ],
  },
  {
    id: "creamy-afghani-alfredo-chicken",
    name: "Creamy Afghani Alfredo chicken",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "gluten"],
    calories: 505,
    protein: 47,
    carbs: 15,
    fat: 30,
    minutes: 45,
    note: "Yogurt-marinated chicken in a light white sauce. Prefer the 505 kcal / 47g version (4 servings).",
    videoUrl: "https://www.instagram.com/p/DTW6jg-iSe4/",
    steps: [
      "Marinate chicken in thick curd, ginger-garlic, spices, and vinegar 30–60 minutes.",
      "Pan-cook or air-fry until browned and done; set aside.",
      "Sauté onion and chillies in light butter; cook atta 1 minute; whisk in skim milk and cheese.",
      "Coat chicken in sauce; simmer 2 minutes; finish with coriander.",
    ],
    ingredients: [
      { item: "Chicken drumsticks/thighs", qty: 250, unit: "g", aisle: "protein" },
      { item: "Thick curd (yogurt)", qty: 50, unit: "g", aisle: "dairy" },
      { item: "Ginger-garlic paste", qty: 0.25, unit: "tbsp", aisle: "pantry" },
      { item: "Light butter", qty: 0.25, unit: "tbsp", aisle: "dairy" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Green chilli", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Whole wheat atta", qty: 0.25, unit: "tbsp", aisle: "pantry" },
      { item: "Skim milk", qty: 45, unit: "ml", aisle: "dairy" },
      { item: "Processed cheese", qty: 2.5, unit: "g", aisle: "dairy" },
      { item: "Coriander", qty: 1, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "creamy-afghani-chicken",
    name: "Creamy Afghani chicken",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "gluten"],
    calories: 480,
    protein: 42,
    carbs: 12,
    fat: 28,
    minutes: 35,
    note: "Quick boneless-thigh version with curd marinade and mozzarella white gravy.",
    videoUrl: "https://www.instagram.com/p/DbVfMt0pdTa/",
    steps: [
      "Marinate chicken in curd, ginger-garlic, spices, lemon, and coriander 20–30 minutes.",
      "Cook in butter until the marinade reduces; remove chicken.",
      "Sauté onion and garlic; cook flour; add milk, spices, and mozzarella until creamy; return chicken.",
    ],
    ingredients: [
      { item: "Chicken thighs (boneless)", qty: 300, unit: "g", aisle: "protein" },
      { item: "Curd (yogurt)", qty: 0.5, unit: "cup", aisle: "dairy" },
      { item: "Ginger-garlic", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Butter", qty: 0.5, unit: "tbsp", aisle: "dairy" },
      { item: "Oil", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Onion (small)", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Flour", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Milk", qty: 0.5, unit: "cup", aisle: "dairy" },
      { item: "Mozzarella", qty: 3.5, unit: "tbsp", aisle: "dairy" },
      { item: "Lemon juice", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Coriander", qty: 2, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "chicken-fajita-rice-bowl",
    name: "Chicken fajita rice bowl",
    slot: "dinner",
    diet: "omnivore",
    allergens: [],
    calories: 650,
    protein: 55,
    carbs: 62,
    fat: 18,
    minutes: 35,
    note: "Air-fryer fajita chicken with peppers, pico, beans, rice, and avocado. Macros trimmed from the 865 kcal double-rice post.",
    videoUrl: "https://www.instagram.com/p/DbRmE4uO1Uk/",
    steps: [
      "Season chicken; air-fry at 385F for 13–20 minutes.",
      "Air-fry peppers and onion in butter and spices 5–7 minutes.",
      "Mix pico; build bowls with rice, black beans, avocado, lettuce, chicken, and peppers.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 170, unit: "g", aisle: "protein" },
      { item: "Cooked Mexican rice", qty: 0.75, unit: "cup", aisle: "pantry" },
      { item: "Black beans", qty: 0.33, unit: "cup", aisle: "pantry" },
      { item: "Bell peppers (mixed)", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "White onion", qty: 0.15, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.4, unit: "cup", aisle: "produce" },
      { item: "Red onion", qty: 2, unit: "tbsp", aisle: "produce" },
      { item: "Jalapeño", qty: 1.5, unit: "tbsp", aisle: "produce" },
      { item: "Avocado", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Lettuce", qty: 1, unit: "cup", aisle: "produce" },
      { item: "Lime juice", qty: 1, unit: "tsp", aisle: "produce" },
      { item: "Butter", qty: 0.25, unit: "tbsp", aisle: "dairy" },
    ],
  },
  {
    id: "lemon-parm-chicken-orzo",
    name: "Lemon parm chicken orzo",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "gluten"],
    calories: 551,
    protein: 50,
    carbs: 54,
    fat: 15,
    minutes: 35,
    note: "One-pan creamy lemon orzo with chicken, peas, and carrots. Macros per serving of 7.",
    videoUrl: "https://www.instagram.com/p/DWJS1nrAMJq/",
    steps: [
      "Cook diced chicken with paprika, garlic powder, salt, and pepper 5–7 minutes.",
      "Add shallot and garlic; toast dry orzo 1–2 minutes.",
      "Add broth, peas, and carrots; cover and simmer 10–12 minutes.",
      "Stir in cream cheese, Parmesan, lemon zest, and juice; divide into 7 servings.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 130, unit: "g", aisle: "protein" },
      { item: "Orzo (dry)", qty: 57, unit: "g", aisle: "pantry" },
      { item: "Chicken broth", qty: 205, unit: "ml", aisle: "pantry" },
      { item: "Shallot", qty: 0.15, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 0.5, unit: "tsp", aisle: "produce" },
      { item: "Frozen peas & carrots", qty: 50, unit: "g", aisle: "frozen" },
      { item: "Reduced-fat cream cheese", qty: 32, unit: "g", aisle: "dairy" },
      { item: "Parmesan", qty: 28, unit: "g", aisle: "dairy" },
      { item: "Lemon", qty: 0.3, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "street-corn-chicken-bowl-simple",
    name: "Street corn chicken bowl",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 520,
    protein: 48,
    carbs: 42,
    fat: 16,
    minutes: 25,
    note: "Seasoned chicken over rice with Greek-yogurt street corn salsa and Tajín.",
    videoUrl: "https://www.instagram.com/p/DYSo5KjxLx6/",
    steps: [
      "Cube and season chicken; cook through 3–4 minutes per side.",
      "Mix corn, Greek yogurt, cotija, lime, jalapeño, cilantro, avocado, and Tajín.",
      "Serve chicken over rice topped with street corn salsa.",
    ],
    ingredients: [
      { item: "Chicken", qty: 170, unit: "g", aisle: "protein" },
      { item: "Cooked rice", qty: 0.75, unit: "cup", aisle: "pantry" },
      { item: "Corn (canned)", qty: 0.5, unit: "cup", aisle: "pantry" },
      { item: "Greek yogurt", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Cotija cheese", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Jalapeño", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Avocado", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Lime", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Cilantro", qty: 1, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "mexican-streetcorn-meal-prep-bowls",
    name: "Mexican streetcorn chicken meal-prep bowls",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "egg"],
    calories: 536,
    protein: 56,
    carbs: 46,
    fat: 10,
    minutes: 35,
    note: "Air-fry seasonings chicken, streetcorn salad, cilantro-lime rice, creamy sauce. Per meal of 4.",
    videoUrl: "https://www.instagram.com/p/DYM4rW7Nq3x/",
    steps: [
      "Toss diced chicken in spices and avocado oil; cook until done.",
      "Mix streetcorn salad: corn, onion, jalapeño, yogurt, light mayo, feta, cilantro, Tajín.",
      "Cook basmati; fold in lime and cilantro. Mix creamy cilantro sauce.",
      "Assemble bowls; keep salad separate for meal prep.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 200, unit: "g", aisle: "protein" },
      { item: "Sweetcorn", qty: 88, unit: "g", aisle: "frozen" },
      { item: "Red onion", qty: 0.15, unit: "ea", aisle: "produce" },
      { item: "Jalapeño", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "0% Greek yogurt", qty: 55, unit: "g", aisle: "dairy" },
      { item: "Light mayo", qty: 1.5, unit: "tbsp", aisle: "pantry" },
      { item: "Low-fat feta", qty: 20, unit: "g", aisle: "dairy" },
      { item: "Basmati rice (dry)", qty: 0.25, unit: "cup", aisle: "pantry" },
      { item: "Lime", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Cilantro", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Avocado oil", qty: 0.5, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "chipotle-honey-chicken-bowl",
    name: "Chipotle honey chicken bowl",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 530,
    protein: 51,
    carbs: 50,
    fat: 17,
    minutes: 40,
    note: "Marinated chipotle-honey thighs over jasmine rice with jalapeño-cilantro green sauce.",
    videoUrl: "https://www.instagram.com/p/DYz1-4Bx-nA/",
    steps: [
      "Blend chipotle, adobo, honey, lime, garlic, oil, salt, and pepper; marinate chicken ≥30 minutes.",
      "Cook rice; pan-sear chicken until caramelized.",
      "Blend Greek yogurt, cilantro, lime, pickled jalapeños, and garlic for green sauce.",
      "Build bowls with rice, chicken, optional pico/guac, and sauce.",
    ],
    ingredients: [
      { item: "Chicken thighs", qty: 227, unit: "g", aisle: "protein" },
      { item: "Chipotle peppers in adobo", qty: 0.75, unit: "ea", aisle: "pantry" },
      { item: "Adobo sauce", qty: 0.75, unit: "tbsp", aisle: "pantry" },
      { item: "Honey", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Lime", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 1.5, unit: "clove", aisle: "produce" },
      { item: "Jasmine rice (uncooked)", qty: 0.25, unit: "cup", aisle: "pantry" },
      { item: "Nonfat Greek yogurt", qty: 42, unit: "g", aisle: "dairy" },
      { item: "Cilantro", qty: 2, unit: "tbsp", aisle: "produce" },
      { item: "Pickled jalapeños", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Olive oil", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "street-corn-chicken-protein-bowl",
    name: "Street corn chicken protein bowl",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "egg"],
    calories: 540,
    protein: 56,
    carbs: 55,
    fat: 12,
    minutes: 30,
    note: "Chili-spiced chicken, yogurt street corn, jasmine rice, creamy cilantro drizzle. Per bowl of 4.",
    videoUrl: "https://www.instagram.com/p/DaYHtSKxI0C/",
    steps: [
      "Season chicken with chili, paprika, garlic, cumin; cook in olive oil.",
      "Mix corn with Greek yogurt, light mayo, lime, cotija, and chili powder.",
      "Blend creamy cilantro drizzle; serve over cooked jasmine rice.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 170, unit: "g", aisle: "protein" },
      { item: "Cooked jasmine rice", qty: 0.5, unit: "cup", aisle: "pantry" },
      { item: "Corn", qty: 0.5, unit: "cup", aisle: "frozen" },
      { item: "Nonfat Greek yogurt", qty: 3, unit: "tbsp", aisle: "dairy" },
      { item: "Light mayo", qty: 0.75, unit: "tbsp", aisle: "pantry" },
      { item: "Cotija or feta", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Lime", qty: 0.4, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 0.25, unit: "clove", aisle: "produce" },
      { item: "Cilantro", qty: 2, unit: "tbsp", aisle: "produce" },
      { item: "Olive oil", qty: 0.75, unit: "tsp", aisle: "pantry" },
    ],
  },

  // ---------- snack ----------
  {
    id: "crispy-chicken-nuggets",
    name: "Air-fryer crispy chicken nuggets",
    slot: "snack",
    diet: "omnivore",
    allergens: ["egg", "dairy"],
    calories: 250,
    protein: 30,
    carbs: 8,
    fat: 10,
    minutes: 25,
    note: "~8 nuggets with garlic yogurt dip. Full plate is 30 nuggets / 948 kcal — this is a snack portion.",
    videoUrl: "https://www.instagram.com/p/DbTPgfiNJ6X/",
    steps: [
      "Mix lean ground chicken with egg, spices, baking soda, and mozzarella.",
      "Wrap portions in rice paper; spray lightly.",
      "Air-fry at 200C for 15–20 minutes, shaking halfway.",
      "Dip: 0% Greek yogurt, light mayo, garlic paste, salt, and a splash of water.",
    ],
    ingredients: [
      { item: "Lean ground chicken", qty: 130, unit: "g", aisle: "protein" },
      { item: "Egg", qty: 0.25, unit: "ea", aisle: "protein" },
      { item: "Mozzarella", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Rice paper sheets", qty: 1.5, unit: "ea", aisle: "pantry" },
      { item: "0% Greek yogurt", qty: 25, unit: "g", aisle: "dairy" },
      { item: "Light mayo", qty: 8, unit: "g", aisle: "pantry" },
      { item: "Garlic paste", qty: 0.15, unit: "tsp", aisle: "pantry" },
    ],
  },
];
