import type { Recipe } from "./recipes";

/**
 * Recipes scraped from Instagram Saved → Meal prep collection
 * (https://www.instagram.com/sandeep.kondury/saved/meal-prep/27631816719823147/).
 * Macros and ingredients are per serving when the caption gave batch sizes.
 * Skip list: duplicate rajma chawal jar, diet-promo post, caption-less meal-prep clip.
 */
export const INSTAGRAM_SAVED_MEALS: Recipe[] = [
  // ---------- breakfast ----------
  {
    id: "oats-whey-breakfast-shake",
    name: "Oats whey breakfast shake",
    slot: "breakfast",
    diet: "vegetarian",
    allergens: ["dairy", "nuts"],
    calories: 760,
    protein: 48,
    carbs: 95,
    fat: 25,
    minutes: 15,
    note: "Macros estimated because the caption lists ingredients but no nutrition; assumes 1.5 bananas and 20g makhana powder.",
    videoUrl: "https://www.instagram.com/reel/DVutaxrEfvl/",
    steps: [
      "Add oats, nuts, raisins, and makhana powder to a blender.",
      "Add banana, honey, peanut butter, whey, and milk.",
      "Blend until smooth, adding water if needed.",
    ],
    ingredients: [
      { item: "Banana", qty: 1.5, unit: "ea", aisle: "produce" },
      { item: "Rolled oats", qty: 2, unit: "scoop", aisle: "pantry" },
      { item: "Walnuts", qty: 5, unit: "ea", aisle: "pantry" },
      { item: "Almonds", qty: 9, unit: "ea", aisle: "pantry" },
      { item: "Makhana (fox nuts)", qty: 20, unit: "g", aisle: "pantry" },
      { item: "Raisins", qty: 11, unit: "ea", aisle: "pantry" },
      { item: "Honey", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Peanut butter", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Protein powder", qty: 1, unit: "scoop", aisle: "fuel" },
      { item: "Milk", qty: 300, unit: "ml", aisle: "dairy" },
    ],
  },
  {
    id: "seeded-oats-breakfast-smoothie",
    name: "Seeded oats breakfast smoothie",
    slot: "breakfast",
    diet: "vegetarian",
    allergens: ["dairy", "nuts"],
    calories: 650,
    protein: 31,
    carbs: 70,
    fat: 29,
    minutes: 15,
    note: "Protein is caption-stated; remaining macros are estimated from ingredients because no full macro breakdown was provided.",
    videoUrl: "https://www.instagram.com/reel/DKMicmCoSfM/",
    steps: [
      "Grind oats, nuts, seeds, and dates.",
      "Add milk and peanut butter.",
      "Blend smooth, thinning with water as needed.",
    ],
    ingredients: [
      { item: "Rolled oats", qty: 60, unit: "g", aisle: "pantry" },
      { item: "Almonds", qty: 5, unit: "ea", aisle: "pantry" },
      { item: "Cashews", qty: 5, unit: "ea", aisle: "pantry" },
      { item: "Pumpkin seeds", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Sunflower seeds", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Chia seeds", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Dates", qty: 2, unit: "ea", aisle: "pantry" },
      { item: "Milk", qty: 250, unit: "ml", aisle: "dairy" },
      { item: "Peanut butter", qty: 1, unit: "tbsp", aisle: "pantry" },
    ],
  },
  {
    id: "blueberry-skyr-protein-smoothie",
    name: "Blueberry skyr protein smoothie",
    slot: "breakfast",
    diet: "vegetarian",
    allergens: ["dairy", "nuts"],
    calories: 570,
    protein: 60,
    carbs: 50,
    fat: 12,
    minutes: 15,
    note: "Macros per smoothie.",
    videoUrl: "https://www.instagram.com/reel/CmJ6GFeoTjz/",
    steps: [
      "Add fruit, protein powder, honey, peanut butter, chia, and skyr to a blender.",
      "Pour in coconut milk.",
      "Blend until thick and creamy.",
    ],
    ingredients: [
      { item: "Frozen blueberries", qty: 120, unit: "g", aisle: "frozen" },
      { item: "Banana", qty: 70, unit: "g", aisle: "produce" },
      { item: "Protein powder", qty: 45, unit: "g", aisle: "fuel" },
      { item: "Honey", qty: 5, unit: "g", aisle: "pantry" },
      { item: "Peanut butter", qty: 10, unit: "g", aisle: "pantry" },
      { item: "Chia seeds", qty: 7, unit: "g", aisle: "pantry" },
      { item: "Greek yogurt", qty: 150, unit: "g", aisle: "dairy" },
      { item: "Coconut milk beverage", qty: 250, unit: "ml", aisle: "dairy" },
    ],
  },
  {
    id: "banana-blueberry-protein-smoothie",
    name: "Banana blueberry protein smoothie",
    slot: "breakfast",
    diet: "vegetarian",
    allergens: ["dairy", "nuts", "gluten"],
    calories: 568,
    protein: 48,
    carbs: 58,
    fat: 16,
    minutes: 15,
    note: "Macros per smoothie.",
    videoUrl: "https://www.instagram.com/reel/CqTmGFnDOFK/",
    steps: [
      "Add banana, blueberries, granola, yogurt, peanut butter, and protein powder to a blender.",
      "Pour in skim milk.",
      "Blend until smooth and serve.",
    ],
    ingredients: [
      { item: "Banana", qty: 80, unit: "g", aisle: "produce" },
      { item: "Blueberries", qty: 80, unit: "g", aisle: "produce" },
      { item: "Protein granola", qty: 25, unit: "g", aisle: "pantry" },
      { item: "Greek yogurt", qty: 50, unit: "g", aisle: "dairy" },
      { item: "Peanut butter", qty: 20, unit: "g", aisle: "pantry" },
      { item: "Protein powder", qty: 30, unit: "g", aisle: "fuel" },
      { item: "Skim milk", qty: 200, unit: "ml", aisle: "dairy" },
    ],
  },
  {
    id: "grilled-cheese-breakfast-burritos",
    name: "Grilled cheese breakfast burritos",
    slot: "breakfast",
    diet: "omnivore",
    allergens: ["dairy", "egg", "gluten"],
    calories: 620,
    protein: 62,
    carbs: 35,
    fat: 25,
    minutes: 45,
    note: "Macros per burrito; batch makes 6.",
    videoUrl: "https://www.instagram.com/reel/DX4cNMRoi1R/",
    steps: [
      "Brown beef with beans, onion, taco seasoning, and tomato paste.",
      "Soft-scramble eggs and egg whites; mix the chipotle yogurt sauce.",
      "Divide beef, eggs, sauce, and mozzarella among tortillas and roll.",
      "Crisp each burrito over bubbling cheddar to form a cheese shell.",
    ],
    ingredients: [
      { item: "Lean ground beef", qty: 133.33, unit: "g", aisle: "protein" },
      { item: "Refried beans", qty: 66.67, unit: "g", aisle: "pantry" },
      { item: "Eggs", qty: 1.33, unit: "ea", aisle: "protein" },
      { item: "Egg white", qty: 20, unit: "ml", aisle: "protein" },
      { item: "Greek yogurt", qty: 33.33, unit: "g", aisle: "dairy" },
      { item: "Low-calorie tortilla", qty: 1, unit: "ea", aisle: "bakery" },
      { item: "Low-fat mozzarella", qty: 25, unit: "g", aisle: "dairy" },
      { item: "Fat-free cheddar", qty: 20, unit: "g", aisle: "dairy" },
      { item: "Taco seasoning", qty: 0.33, unit: "tbsp", aisle: "pantry" },
      { item: "Chipotle chilli paste", qty: 0.17, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "crispy-potato-egg-breakfast-prep",
    name: "Crispy potato and egg breakfast prep",
    slot: "breakfast",
    diet: "omnivore",
    allergens: ["dairy", "egg"],
    calories: 435,
    protein: 28,
    carbs: 39,
    fat: 17,
    minutes: 35,
    note: "Macros per serving; batch makes 4.",
    videoUrl: "https://www.instagram.com/reel/Crv2aj1oLM1/",
    steps: [
      "Microwave potatoes briefly, then season and pan-crisp.",
      "Sauté onion, bell pepper, and turkey bacon with the potatoes.",
      "Slowly scramble eggs and egg whites with cream cheese.",
      "Divide into four containers and finish with spicy mayo.",
    ],
    ingredients: [
      { item: "Potatoes", qty: 200, unit: "g", aisle: "produce" },
      { item: "Red onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Red bell pepper", qty: 0.12, unit: "ea", aisle: "produce" },
      { item: "Turkey bacon", qty: 40, unit: "g", aisle: "protein" },
      { item: "Eggs", qty: 1, unit: "ea", aisle: "protein" },
      { item: "Egg white", qty: 2, unit: "ea", aisle: "protein" },
      { item: "Reduced-fat cream cheese", qty: 25, unit: "g", aisle: "dairy" },
      { item: "Sriracha mayonnaise", qty: 10, unit: "g", aisle: "pantry" },
    ],
  },

  // ---------- lunch ----------
  {
    id: "rajma-chawal-paneer-jar",
    name: "Rajma chawal paneer jar",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 457,
    protein: 44,
    carbs: 54,
    fat: 6,
    minutes: 20,
    note: "Macros per jar.",
    videoUrl: "https://www.instagram.com/reel/DaunwR_IEq4/",
    steps: [
      "Air-fry the paneer until golden.",
      "Mix rajma, rice, vegetables, yogurt, lime, and seasonings.",
      "Layer in a jar and top with paneer and cilantro.",
    ],
    ingredients: [
      { item: "Boiled rajma (kidney beans)", qty: 100, unit: "g", aisle: "pantry" },
      { item: "Cooked rice", qty: 100, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Greek yogurt", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Cucumber", qty: 50, unit: "g", aisle: "produce" },
      { item: "Rajma masala", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Cilantro", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Lime", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "mexican-rajma-paneer-salad-jars",
    name: "Mexican rajma paneer salad jars",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 320,
    protein: 15,
    carbs: 35,
    fat: 14,
    minutes: 25,
    note: "Estimated macros per jar; caption makes 4 jars and provides no nutrition.",
    videoUrl: "https://www.instagram.com/reel/Dbn--xZSUqI/",
    steps: [
      "Sauté mashed rajma and paneer with peri-peri seasoning.",
      "Air-fry the seasoned sweet corn until crisp.",
      "Mix yogurt, cilantro, and lime for the dressing.",
      "Divide vegetables, rajma-paneer, corn, and dressing among four jars.",
    ],
    ingredients: [
      { item: "Boiled rajma (kidney beans)", qty: 0.38, unit: "cup", aisle: "pantry" },
      { item: "Paneer", qty: 25, unit: "g", aisle: "dairy" },
      { item: "Sweet corn", qty: 0.38, unit: "cup", aisle: "frozen" },
      { item: "Olive oil", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Curd (yogurt)", qty: 0.12, unit: "cup", aisle: "dairy" },
      { item: "Cilantro", qty: 0.5, unit: "tbsp", aisle: "produce" },
      { item: "Lime", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Cucumber", qty: 0.25, unit: "cup", aisle: "produce" },
      { item: "Tomato", qty: 0.25, unit: "cup", aisle: "produce" },
      { item: "Peri-peri seasoning", qty: 0.5, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "rajma-paneer-sprout-jar",
    name: "Rajma paneer sprout jar",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy", "nuts"],
    calories: 336,
    protein: 34,
    carbs: 20,
    fat: 10,
    minutes: 20,
    note: "Macros per jar.",
    videoUrl: "https://www.instagram.com/reel/DbsUXnxo8mp/",
    steps: [
      "Air-fry paneer until lightly crisp.",
      "Combine rajma, sprouts, vegetables, peanuts, lime, and spices.",
      "Pack into a jar and top with paneer and cilantro.",
    ],
    ingredients: [
      { item: "Boiled rajma (kidney beans)", qty: 100, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Sprouts", qty: 50, unit: "g", aisle: "produce" },
      { item: "Peanuts", qty: 10, unit: "g", aisle: "pantry" },
      { item: "Carrot", qty: 50, unit: "g", aisle: "produce" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Chaat masala", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Lime", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "chole-masala-oats",
    name: "Chole masala oats",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 290,
    protein: 12,
    carbs: 47,
    fat: 7,
    minutes: 25,
    note: "Macros per serving; batch serves 2.",
    videoUrl: "https://www.instagram.com/reel/Dbf7HW-CgHj/",
    steps: [
      "Bloom cumin in ghee and sauté onion.",
      "Cook tomato, chilli, and spices until jammy.",
      "Stir in chickpeas and water and bring to a boil.",
      "Add oats and simmer until creamy; garnish with cilantro.",
    ],
    ingredients: [
      { item: "Rolled oats", qty: 0.38, unit: "cup", aisle: "pantry" },
      { item: "Cooked chickpeas", qty: 0.5, unit: "cup", aisle: "pantry" },
      { item: "Ghee", qty: 0.5, unit: "tsp", aisle: "dairy" },
      { item: "Cumin seeds", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Onion", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Green chilli", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Chole masala", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "honey-cajun-chicken-burritos",
    name: "Honey Cajun chicken burritos",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["dairy", "gluten"],
    calories: 500,
    protein: 65,
    carbs: 42,
    fat: 8,
    minutes: 45,
    note: "Macros per burrito; batch makes 10.",
    videoUrl: "https://www.instagram.com/reel/Db0_vdvoxPJ/",
    steps: [
      "Cook seasoned chicken with garlic, tomato paste, honey, onion, and bell pepper.",
      "Blend cottage cheese, parmesan, milk, Cajun seasoning, honey, and tomato paste into sauce.",
      "Fill tortillas with rice, chicken, sauce, and mozzarella.",
      "Roll tightly and toast, or freeze for later.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 170, unit: "g", aisle: "protein" },
      { item: "Cajun seasoning", qty: 5, unit: "g", aisle: "pantry" },
      { item: "Honey", qty: 6, unit: "g", aisle: "pantry" },
      { item: "Bell pepper", qty: 20, unit: "g", aisle: "produce" },
      { item: "Fat-free mozzarella", qty: 40, unit: "g", aisle: "dairy" },
      { item: "Cooked rice", qty: 60, unit: "g", aisle: "pantry" },
      { item: "Low-calorie tortilla", qty: 1, unit: "ea", aisle: "bakery" },
      { item: "Cottage cheese", qty: 56.5, unit: "g", aisle: "dairy" },
      { item: "Parmesan", qty: 6, unit: "g", aisle: "dairy" },
      { item: "Tomato paste", qty: 9, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "taco-tilapia-bowls",
    name: "Taco tilapia bowls",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["fish"],
    calories: 480,
    protein: 40,
    carbs: 62,
    fat: 8,
    minutes: 30,
    note: "Macros and tilapia quantity estimated because the caption omits nutrition and fish amount; rice recipe is a batch.",
    videoUrl: "https://www.instagram.com/reel/CsXH6x8rAg2/",
    steps: [
      "Season tilapia with taco seasoning and lemon, then cook until flaky.",
      "Sauté onion and garlic, toast the rice, add tomato bouillon water, and simmer covered.",
      "Steam broccoli.",
      "Divide rice, tilapia, and broccoli among bowls.",
    ],
    ingredients: [
      { item: "Tilapia fillet", qty: 150, unit: "g", aisle: "protein" },
      { item: "Taco seasoning", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Lemon", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Rice (uncooked)", qty: 0.5, unit: "cup", aisle: "pantry" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 0.75, unit: "clove", aisle: "produce" },
      { item: "Chicken bouillon", qty: 0.5, unit: "ea", aisle: "pantry" },
      { item: "Broccoli", qty: 0.75, unit: "cup", aisle: "frozen" },
    ],
  },
  {
    id: "paneer-sprout-jar",
    name: "Paneer sprout jar",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy", "nuts"],
    calories: 410,
    protein: 44,
    carbs: 16,
    fat: 16,
    minutes: 20,
    note: "Macros per jar using low-fat paneer.",
    videoUrl: "https://www.instagram.com/reel/DTKiLXkiIya/",
    steps: [
      "Air-fry paneer until golden.",
      "Combine sprouts, corn, chopped vegetables, peanuts, lime, cilantro, and spices.",
      "Pack into a jar and top with paneer.",
    ],
    ingredients: [
      { item: "Low-fat paneer", qty: 150, unit: "g", aisle: "dairy" },
      { item: "Peanuts", qty: 15, unit: "g", aisle: "pantry" },
      { item: "Sprouts", qty: 50, unit: "g", aisle: "produce" },
      { item: "Sweet corn", qty: 50, unit: "g", aisle: "frozen" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Cucumber", qty: 50, unit: "g", aisle: "produce" },
      { item: "Chaat masala", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Lime", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "three-way-paneer-marinade-prep",
    name: "Three-way paneer marinade prep",
    slot: "lunch",
    diet: "omnivore",
    allergens: ["dairy", "soy", "shellfish"],
    calories: 560,
    protein: 38,
    carbs: 18,
    fat: 36,
    minutes: 15,
    note: "Marinade prep guide for 200g paneer (three sauces). Macros estimated; oyster sauce makes one marinade non-vegetarian.",
    videoUrl: "https://www.instagram.com/reel/CwNOA6VNQxm/",
    steps: [
      "Divide paneer among three airtight containers.",
      "Mix soy-oyster, spiced-yogurt, and coconut marinades separately.",
      "Coat each paneer portion and refrigerate up to three days.",
      "Pan-sear or air-fry a portion when ready to eat.",
    ],
    ingredients: [
      { item: "Paneer", qty: 200, unit: "g", aisle: "dairy" },
      { item: "Soy sauce", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Oyster sauce", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Ginger-garlic paste", qty: 3, unit: "tsp", aisle: "pantry" },
      { item: "Lemon", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Yogurt", qty: 2, unit: "tsp", aisle: "dairy" },
      { item: "Coconut milk", qty: 2, unit: "tsp", aisle: "pantry" },
      { item: "Red chilli powder", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Turmeric powder", qty: 0.5, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "paneer-chickpea-herb-rice",
    name: "Paneer chickpea herb rice",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 562,
    protein: 31,
    carbs: 77,
    fat: 14,
    minutes: 25,
    note: "Macros per serving; batch serves 3.",
    videoUrl: "https://www.instagram.com/reel/DPTqbafDetr/",
    steps: [
      "Sauté chickpeas and paneer in oil until lightly golden.",
      "Season with oregano, chilli flakes, and peri-peri.",
      "Fold in cooked rice and cilantro.",
      "Divide into three meal-prep containers.",
    ],
    ingredients: [
      { item: "Cooked chickpeas", qty: 100, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Cooked rice", qty: 150, unit: "g", aisle: "pantry" },
      { item: "Olive oil", qty: 0.33, unit: "tbsp", aisle: "pantry" },
      { item: "Oregano", qty: 0.33, unit: "tsp", aisle: "pantry" },
      { item: "Chilli flakes", qty: 0.33, unit: "tsp", aisle: "pantry" },
      { item: "Peri-peri seasoning", qty: 0.33, unit: "tsp", aisle: "pantry" },
      { item: "Cilantro", qty: 0.67, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "high-protein-veg-pulao",
    name: "High-protein paneer veg pulao",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 555,
    protein: 26,
    carbs: 72,
    fat: 14,
    minutes: 35,
    note: "Macros per serving; batch serves 3.",
    videoUrl: "https://www.instagram.com/reel/DOLMIFwAFoG/",
    steps: [
      "Bloom whole spices in ghee and sauté onion and ginger-garlic paste.",
      "Cook tomato and ground spices until fragrant.",
      "Add cauliflower, carrot, beans, peas, and paneer.",
      "Fold in cooked rice and cilantro; divide into three portions.",
    ],
    ingredients: [
      { item: "Low-fat paneer", qty: 133.33, unit: "g", aisle: "dairy" },
      { item: "Cooked rice", qty: 166.67, unit: "g", aisle: "pantry" },
      { item: "Ghee", qty: 0.67, unit: "tsp", aisle: "dairy" },
      { item: "Onion", qty: 0.67, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.33, unit: "ea", aisle: "produce" },
      { item: "Cauliflower", qty: 0.33, unit: "cup", aisle: "produce" },
      { item: "Carrot", qty: 0.17, unit: "cup", aisle: "produce" },
      { item: "Green beans", qty: 0.17, unit: "cup", aisle: "produce" },
      { item: "Peas", qty: 0.17, unit: "cup", aisle: "frozen" },
      { item: "Garam masala", qty: 0.33, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "yogurt-paneer-salad-jar",
    name: "Yogurt paneer salad jar",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 358,
    protein: 44,
    carbs: 17,
    fat: 8,
    minutes: 20,
    note: "Macros per jar.",
    videoUrl: "https://www.instagram.com/reel/DQ3zuvnCIoA/",
    steps: [
      "Air-fry paneer until golden.",
      "Season yogurt with lime, cumin, chilli flakes, salt, and pepper.",
      "Layer yogurt, cucumber, corn, onion, tomato, lettuce, paneer, and cilantro in a jar.",
    ],
    ingredients: [
      { item: "Low-fat paneer", qty: 150, unit: "g", aisle: "dairy" },
      { item: "Cucumber", qty: 50, unit: "g", aisle: "produce" },
      { item: "Sweet corn", qty: 40, unit: "g", aisle: "frozen" },
      { item: "Onion", qty: 50, unit: "g", aisle: "produce" },
      { item: "Tomato", qty: 50, unit: "g", aisle: "produce" },
      { item: "Lettuce", qty: 1, unit: "handful", aisle: "produce" },
      { item: "Low-fat yogurt", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Lime", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "paneer-shawarma-rice-bowl",
    name: "Paneer shawarma rice bowl",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 700,
    protein: 45,
    carbs: 82,
    fat: 22,
    minutes: 40,
    note: "Protein is caption-stated; other macros estimated. Garlic sauce recipe was omitted, so a simple yogurt-garlic sauce is used.",
    videoUrl: "https://www.instagram.com/reel/DWJaSxXEmBt/",
    steps: [
      "Sauté garlic, chillies, and onion; toast rice with spices, then simmer with water and lemon.",
      "Marinate paneer in yogurt and spices, then pan-char and slice.",
      "Toss chopped vegetables with lemon, salt, and pepper.",
      "Assemble rice, salad, paneer, and yogurt-garlic sauce.",
    ],
    ingredients: [
      { item: "Basmati rice (uncooked)", qty: 0.5, unit: "cup", aisle: "pantry" },
      { item: "Paneer", qty: 200, unit: "g", aisle: "dairy" },
      { item: "Curd (yogurt)", qty: 0.5, unit: "cup", aisle: "dairy" },
      { item: "Garlic", qty: 5, unit: "clove", aisle: "produce" },
      { item: "Onion", qty: 1.5, unit: "ea", aisle: "produce" },
      { item: "Green chillies", qty: 2, unit: "ea", aisle: "produce" },
      { item: "Cucumber", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Bell pepper", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Carrot", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Lemon", qty: 1, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "peanut-soya-jar",
    name: "Peanut soya jar",
    slot: "lunch",
    diet: "vegan",
    allergens: ["nuts", "soy"],
    calories: 390,
    protein: 37,
    carbs: 24,
    fat: 15,
    minutes: 20,
    note: "Macros per jar.",
    videoUrl: "https://www.instagram.com/reel/DYg7NZeo37_/",
    steps: [
      "Pan-fry soaked soya chunks until browned.",
      "Whisk peanut butter, soy sauce, lime, ginger, and warm water.",
      "Layer lettuce, carrot, onion, and soya in a jar.",
      "Add peanut sauce, seasonings, sesame seeds, and lime.",
    ],
    ingredients: [
      { item: "Dry soya chunks", qty: 60, unit: "g", aisle: "pantry" },
      { item: "Peanut butter", qty: 25, unit: "g", aisle: "pantry" },
      { item: "Soy sauce", qty: 10, unit: "g", aisle: "pantry" },
      { item: "Lettuce", qty: 1, unit: "handful", aisle: "produce" },
      { item: "Carrot", qty: 50, unit: "g", aisle: "produce" },
      { item: "Onion", qty: 40, unit: "g", aisle: "produce" },
      { item: "Lime juice", qty: 10, unit: "g", aisle: "produce" },
      { item: "Ginger", qty: 5, unit: "g", aisle: "produce" },
      { item: "Sesame seeds", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "yogurt-soya-chunks-jar",
    name: "Yogurt soya chunks jar",
    slot: "lunch",
    diet: "vegetarian",
    allergens: ["dairy", "soy", "nuts"],
    calories: 370,
    protein: 40,
    carbs: 28,
    fat: 10,
    minutes: 20,
    note: "Macros per jar.",
    videoUrl: "https://www.instagram.com/reel/DPdkjXhCEpy/",
    steps: [
      "Soak and drain soya chunks, then pan-fry with ghee and spices.",
      "Season Greek yogurt with cumin, chaat masala, chilli, salt, and lime.",
      "Layer yogurt, vegetables, peanuts, and soya in a jar.",
      "Chill or shake and serve immediately.",
    ],
    ingredients: [
      { item: "Dry soya chunks", qty: 60, unit: "g", aisle: "pantry" },
      { item: "Ghee", qty: 5, unit: "g", aisle: "dairy" },
      { item: "Onion", qty: 50, unit: "g", aisle: "produce" },
      { item: "Tomato", qty: 50, unit: "g", aisle: "produce" },
      { item: "Cucumber", qty: 50, unit: "g", aisle: "produce" },
      { item: "Carrot", qty: 40, unit: "g", aisle: "produce" },
      { item: "Greek yogurt", qty: 100, unit: "g", aisle: "dairy" },
      { item: "Peanuts", qty: 10, unit: "g", aisle: "pantry" },
      { item: "Lime", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "soya-vegetable-rice-bowl",
    name: "Soya vegetable rice bowl",
    slot: "lunch",
    diet: "vegan",
    allergens: ["soy"],
    calories: 489,
    protein: 33,
    carbs: 69,
    fat: 7,
    minutes: 35,
    note: "Macros per serving; batch serves 3.",
    videoUrl: "https://www.instagram.com/reel/DMVSfKYNH_A/",
    steps: [
      "Sauté cumin, onion, and ginger-garlic paste in oil.",
      "Add carrot, bell pepper, peas, and spices and cook until tender.",
      "Stir in soaked minced soya chunks and cook through.",
      "Fold in cooked rice and cilantro; divide into three containers.",
    ],
    ingredients: [
      { item: "Dry soya chunks", qty: 50, unit: "g", aisle: "pantry" },
      { item: "Cooked rice", qty: 166.67, unit: "g", aisle: "pantry" },
      { item: "Olive oil", qty: 0.33, unit: "tbsp", aisle: "pantry" },
      { item: "Cumin seeds", qty: 0.33, unit: "tsp", aisle: "pantry" },
      { item: "Onion", qty: 0.33, unit: "ea", aisle: "produce" },
      { item: "Ginger-garlic paste", qty: 0.33, unit: "tsp", aisle: "pantry" },
      { item: "Carrot", qty: 0.33, unit: "ea", aisle: "produce" },
      { item: "Bell pepper", qty: 0.33, unit: "cup", aisle: "produce" },
      { item: "Peas", qty: 33.33, unit: "g", aisle: "frozen" },
      { item: "Cilantro", qty: 0.67, unit: "tbsp", aisle: "produce" },
    ],
  },

  // ---------- dinner ----------
  {
    id: "chilli-tilapia-rice-plate",
    name: "Chilli tilapia rice plate",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["fish", "egg"],
    calories: 520,
    protein: 42,
    carbs: 58,
    fat: 14,
    minutes: 35,
    note: "Macros and unspecified fish, rice, and pico quantities estimated from a typical single plate; caption provides no nutrition.",
    videoUrl: "https://www.instagram.com/reel/DTjMOtEEtjK/",
    steps: [
      "Toast the dried chillies, garlic, and onion in oil.",
      "Blend with bouillon, chipotle, mayonnaise, and water.",
      "Season and griddle the tilapia in butter until flaky.",
      "Serve with sauce, rice, pico de gallo, and lettuce.",
    ],
    ingredients: [
      { item: "Tilapia fillet", qty: 200, unit: "g", aisle: "protein" },
      { item: "Dried red chillies", qty: 10, unit: "ea", aisle: "pantry" },
      { item: "Garlic", qty: 2, unit: "clove", aisle: "produce" },
      { item: "Chipotle peppers in adobo", qty: 1, unit: "ea", aisle: "pantry" },
      { item: "Mayonnaise", qty: 1, unit: "tbsp", aisle: "pantry" },
      { item: "Cooked rice", qty: 150, unit: "g", aisle: "pantry" },
      { item: "Pico de gallo", qty: 0.5, unit: "cup", aisle: "produce" },
      { item: "Lettuce", qty: 1, unit: "cup", aisle: "produce" },
    ],
  },
  {
    id: "korean-shrimp-fried-rice",
    name: "Korean shrimp fried rice",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["shellfish", "egg", "soy"],
    calories: 582,
    protein: 53,
    carbs: 68,
    fat: 10,
    minutes: 30,
    note: "Macros per meal; batch serves 4.",
    videoUrl: "https://www.instagram.com/reel/DIgz1WAs1Ia/",
    steps: [
      "Marinate shrimp with ginger, oyster sauce, sesame oil, and seasonings; sear.",
      "Scramble eggs, then sauté green onion, garlic, gochujang, and vegetables.",
      "Fry the cold rice with soy and oyster sauces.",
      "Fold in shrimp and eggs; garnish with sesame and green onion.",
    ],
    ingredients: [
      { item: "Shrimp", qty: 200, unit: "g", aisle: "protein" },
      { item: "Oyster sauce", qty: 10, unit: "ml", aisle: "pantry" },
      { item: "Sesame oil", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Eggs", qty: 0.75, unit: "ea", aisle: "protein" },
      { item: "Spring onions", qty: 15, unit: "g", aisle: "produce" },
      { item: "Garlic", qty: 5, unit: "g", aisle: "produce" },
      { item: "Gochujang", qty: 7.5, unit: "g", aisle: "pantry" },
      { item: "Mixed veggies", qty: 37.5, unit: "g", aisle: "frozen" },
      { item: "Cooked rice", qty: 150, unit: "g", aisle: "pantry" },
      { item: "Soy sauce", qty: 7.5, unit: "ml", aisle: "pantry" },
    ],
  },
  {
    id: "lemon-garlic-shrimp-linguine",
    name: "Lemon garlic shrimp linguine",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["shellfish", "dairy", "gluten"],
    calories: 490,
    protein: 51,
    carbs: 45,
    fat: 11,
    minutes: 30,
    note: "Macros per serving; batch serves 4.",
    videoUrl: "https://www.instagram.com/reel/Cx_YIyZIB0m/",
    steps: [
      "Season and sear shrimp; finish with butter, parsley, and lemon.",
      "On low heat, stir milk and cream cheese into the pan until smooth.",
      "Add parmesan, spinach, pasta water, and linguine.",
      "Fold in shrimp and finish with lemon.",
    ],
    ingredients: [
      { item: "Shrimp", qty: 200, unit: "g", aisle: "protein" },
      { item: "Garlic", qty: 0.75, unit: "clove", aisle: "produce" },
      { item: "Lemon", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Light butter", qty: 10, unit: "g", aisle: "dairy" },
      { item: "Milk", qty: 62.5, unit: "ml", aisle: "dairy" },
      { item: "Reduced-fat cream cheese", qty: 30, unit: "g", aisle: "dairy" },
      { item: "Parmesan", qty: 10, unit: "g", aisle: "dairy" },
      { item: "Linguine (cooked)", qty: 125, unit: "g", aisle: "pantry" },
      { item: "Spinach", qty: 0.25, unit: "cup", aisle: "produce" },
    ],
  },
  {
    id: "garlic-herb-shrimp-bowls",
    name: "Garlic herb shrimp bowls",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["shellfish", "dairy"],
    calories: 442,
    protein: 44,
    carbs: 51,
    fat: 10,
    minutes: 45,
    note: "Macros per serving; batch serves 6.",
    videoUrl: "https://www.instagram.com/reel/DbjLgvMpkBP/",
    steps: [
      "Season and roast cubed potatoes until crisp.",
      "Roast seasoned carrots and onions until tender.",
      "Sear shrimp in batches with butter and garlic.",
      "Finish shrimp with lemon and parsley, then divide all components into six bowls.",
    ],
    ingredients: [
      { item: "Shrimp", qty: 200, unit: "g", aisle: "protein" },
      { item: "Potatoes", qty: 275, unit: "g", aisle: "produce" },
      { item: "Carrot", qty: 100, unit: "g", aisle: "produce" },
      { item: "Onion", qty: 0.33, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 1.17, unit: "clove", aisle: "produce" },
      { item: "Butter", qty: 10, unit: "g", aisle: "dairy" },
      { item: "Olive oil", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Italian seasoning", qty: 0.42, unit: "tsp", aisle: "pantry" },
      { item: "Lemon", qty: 0.17, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "garlic-shrimp-fried-rice",
    name: "Garlic shrimp fried rice",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["shellfish", "egg", "soy"],
    calories: 503,
    protein: 46,
    carbs: 47,
    fat: 13,
    minutes: 30,
    note: "Macros per serving; batch serves 4.",
    videoUrl: "https://www.instagram.com/reel/C61sb_-oKsa/",
    steps: [
      "Marinate shrimp in soy sauce and spices, then sear in butter.",
      "Mix mayonnaise, ketchup, sriracha, rice vinegar, paprika, and ginger for the sauce.",
      "Stir-fry garlic, green onion, carrots, peas, and eggs.",
      "Add cold rice, soy and oyster sauces; serve with shrimp and yum-yum sauce.",
    ],
    ingredients: [
      { item: "Shrimp", qty: 200, unit: "g", aisle: "protein" },
      { item: "Soy sauce", qty: 13.75, unit: "ml", aisle: "pantry" },
      { item: "Light butter", qty: 7.5, unit: "g", aisle: "dairy" },
      { item: "Light mayo", qty: 20, unit: "g", aisle: "pantry" },
      { item: "Sriracha", qty: 6.25, unit: "g", aisle: "pantry" },
      { item: "Spring onions", qty: 20, unit: "g", aisle: "produce" },
      { item: "Carrot", qty: 25, unit: "g", aisle: "frozen" },
      { item: "Peas", qty: 25, unit: "g", aisle: "frozen" },
      { item: "Eggs", qty: 1, unit: "ea", aisle: "protein" },
      { item: "Cooked rice", qty: 135, unit: "g", aisle: "pantry" },
      { item: "Oyster sauce", qty: 7.5, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "schezwan-prawn-rice",
    name: "Schezwan prawn rice",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["shellfish", "soy"],
    calories: 483,
    protein: 44,
    carbs: 50,
    fat: 8,
    minutes: 25,
    note: "Macros per serving; batch serves 3.",
    videoUrl: "https://www.instagram.com/reel/DRPLKVBjYZy/",
    steps: [
      "Sauté garlic and green chillies in oil.",
      "Add prawns and cook until nearly opaque.",
      "Stir in rice, Schezwan sauce, vinegar, soy sauce, and chilli sauce.",
      "Finish with spring onions and divide into three portions.",
    ],
    ingredients: [
      { item: "Shrimp", qty: 166.67, unit: "g", aisle: "protein" },
      { item: "Cooked rice", qty: 166.67, unit: "g", aisle: "pantry" },
      { item: "Garlic", qty: 3.33, unit: "clove", aisle: "produce" },
      { item: "Green chillies", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Spring onions", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Schezwan sauce", qty: 0.67, unit: "tbsp", aisle: "pantry" },
      { item: "Soy sauce", qty: 0.33, unit: "tbsp", aisle: "pantry" },
      { item: "Chilli sauce", qty: 0.67, unit: "tbsp", aisle: "pantry" },
      { item: "Olive oil", qty: 0.33, unit: "tbsp", aisle: "pantry" },
    ],
  },
  {
    id: "one-pan-chicken-fajita-rice",
    name: "One-pan chicken fajita rice",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "egg"],
    calories: 408,
    protein: 39,
    carbs: 41,
    fat: 9,
    minutes: 35,
    note: "Macros per serving; batch serves 4. Mayonnaise allergen assumes standard egg-based mayo.",
    videoUrl: "https://www.instagram.com/reel/Cs6yBsGIkhh/",
    steps: [
      "Season and sear chicken fillets until crusted and cooked through.",
      "Toast rice with onions, bell peppers, and spices.",
      "Add water, cover, and simmer until rice is tender.",
      "Blend yogurt, mayo, garlic, cilantro, and lemon; serve over chicken and rice.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 150, unit: "g", aisle: "protein" },
      { item: "Basmati rice (uncooked)", qty: 57.5, unit: "g", aisle: "pantry" },
      { item: "Red onion", qty: 0.12, unit: "ea", aisle: "produce" },
      { item: "White onion", qty: 0.12, unit: "ea", aisle: "produce" },
      { item: "Red bell pepper", qty: 0.12, unit: "ea", aisle: "produce" },
      { item: "Bell pepper", qty: 0.12, unit: "ea", aisle: "produce" },
      { item: "Greek yogurt", qty: 50, unit: "g", aisle: "dairy" },
      { item: "Light mayo", qty: 15, unit: "g", aisle: "pantry" },
      { item: "Garlic", qty: 1, unit: "clove", aisle: "produce" },
      { item: "Cilantro", qty: 0.25, unit: "handful", aisle: "produce" },
    ],
  },
  {
    id: "bang-bang-chicken-coconut-rice",
    name: "Bang bang chicken coconut rice bowls",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "egg"],
    calories: 595,
    protein: 46,
    carbs: 51,
    fat: 22,
    minutes: 40,
    note: "Macros per serving; batch serves 5. Mayonnaise allergen assumes standard egg-based mayo.",
    videoUrl: "https://www.instagram.com/reel/DGY6HOnIQMh/",
    steps: [
      "Season chicken and coat lightly with mixed bang-bang sauce.",
      "Bake or air-fry at 200°C until crisp and cooked through.",
      "Sauté onion and garlic with butter, spices, and coconut; fold in cooked rice.",
      "Divide rice and chicken into bowls and finish with extra sauce.",
    ],
    ingredients: [
      { item: "Chicken thighs", qty: 200, unit: "g", aisle: "protein" },
      { item: "Light mayo", qty: 20, unit: "g", aisle: "pantry" },
      { item: "Fat-free yogurt", qty: 12, unit: "g", aisle: "dairy" },
      { item: "Sweet chilli sauce", qty: 10, unit: "g", aisle: "pantry" },
      { item: "Sriracha", qty: 10, unit: "g", aisle: "pantry" },
      { item: "Rice (uncooked)", qty: 52, unit: "g", aisle: "pantry" },
      { item: "Light butter", qty: 4, unit: "g", aisle: "dairy" },
      { item: "Garlic", qty: 7, unit: "g", aisle: "produce" },
      { item: "Onion", qty: 34, unit: "g", aisle: "produce" },
      { item: "Desiccated coconut", qty: 7, unit: "g", aisle: "pantry" },
    ],
  },
  {
    id: "creamy-lemon-butter-chicken-rice",
    name: "Creamy lemon butter chicken rice",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 360,
    protein: 33,
    carbs: 38,
    fat: 11,
    minutes: 35,
    note: "Macros per meal; batch makes 5 servings.",
    videoUrl: "https://www.instagram.com/reel/CpIhxAOJVTF/",
    steps: [
      "Season chicken with lemon, garlic, onion powder, oregano, chilli, and oil; cook until golden.",
      "On low heat, sauté butter, garlic, onion, and tomatoes.",
      "Add milk, cream cheese, spinach, and chicken; simmer until creamy.",
      "Boil rice and divide with chicken among five containers.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 120, unit: "g", aisle: "protein" },
      { item: "Rice (uncooked)", qty: 40, unit: "g", aisle: "pantry" },
      { item: "Light butter", qty: 6, unit: "g", aisle: "dairy" },
      { item: "Garlic", qty: 0.4, unit: "tbsp", aisle: "produce" },
      { item: "Onion", qty: 0.2, unit: "ea", aisle: "produce" },
      { item: "Cherry tomatoes", qty: 0.2, unit: "cup", aisle: "produce" },
      { item: "Skim milk", qty: 40, unit: "ml", aisle: "dairy" },
      { item: "Reduced-fat cream cheese", qty: 12, unit: "g", aisle: "dairy" },
      { item: "Spinach", qty: 0.4, unit: "cup", aisle: "produce" },
      { item: "Lemon", qty: 0.2, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "lemon-pepper-chicken-rice-bowls",
    name: "Lemon pepper chicken rice bowls",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "egg"],
    calories: 531,
    protein: 46,
    carbs: 46,
    fat: 17,
    minutes: 40,
    note: "Macros per serving; batch serves 4. Mayonnaise allergen assumes standard egg-based mayo.",
    videoUrl: "https://www.instagram.com/reel/DMf4ak2qNcY/",
    steps: [
      "Marinate chicken with lemon, spices, and oil, then sear until golden.",
      "Sauté garlic and onion with spices; fold in cooked rice and parsley.",
      "Mix yogurt, mayo, Dijon, lemon, herbs, tomato, and cucumber for ranch salad.",
      "Divide into bowls, keeping salad separate for reheating.",
    ],
    ingredients: [
      { item: "Chicken thighs", qty: 200, unit: "g", aisle: "protein" },
      { item: "Lemon", qty: 0.38, unit: "ea", aisle: "produce" },
      { item: "Light butter", qty: 3.75, unit: "g", aisle: "dairy" },
      { item: "Cooked rice", qty: 135, unit: "g", aisle: "pantry" },
      { item: "Onion", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Fat-free yogurt", qty: 37.5, unit: "g", aisle: "dairy" },
      { item: "Light mayo", qty: 20, unit: "g", aisle: "pantry" },
      { item: "Mustard", qty: 0.25, unit: "tsp", aisle: "pantry" },
      { item: "Tomato", qty: 37.5, unit: "g", aisle: "produce" },
      { item: "Cucumber", qty: 25, unit: "g", aisle: "produce" },
    ],
  },
  {
    id: "creamy-chipotle-chicken-potatoes",
    name: "Creamy chipotle chicken and potatoes",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 548,
    protein: 51,
    carbs: 52,
    fat: 17,
    minutes: 45,
    note: "Macros per serving; batch serves 6.",
    videoUrl: "https://www.instagram.com/reel/DXE-5Uugvem/",
    steps: [
      "Marinate chicken with spices, chipotle, lime, and oil.",
      "Roast seasoned potatoes and chicken on separate sheet pans at 200°C.",
      "Cook red onion, butter, seasoning, and chipotle until caramelized.",
      "Stir in evaporated milk and cream cheese; coat potatoes in sauce and serve with chicken.",
    ],
    ingredients: [
      { item: "Chicken thighs", qty: 200, unit: "g", aisle: "protein" },
      { item: "Chipotle chilli paste", qty: 28.33, unit: "g", aisle: "pantry" },
      { item: "Lime", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Potatoes", qty: 216.67, unit: "g", aisle: "produce" },
      { item: "Light butter", qty: 3.33, unit: "g", aisle: "dairy" },
      { item: "Red onion", qty: 29.17, unit: "g", aisle: "produce" },
      { item: "Evaporated milk", qty: 66.67, unit: "g", aisle: "dairy" },
      { item: "Reduced-fat cream cheese", qty: 18.33, unit: "g", aisle: "dairy" },
      { item: "Smoked paprika", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "creamy-tuscan-butter-chicken-rice",
    name: "Creamy Tuscan butter chicken rice",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy"],
    calories: 360,
    protein: 35,
    carbs: 36,
    fat: 9,
    minutes: 35,
    note: "Macros per meal; batch makes 5 servings.",
    videoUrl: "https://www.instagram.com/reel/CoFXQv-qWy1/",
    steps: [
      "Season chicken with oregano, oil, garlic, cumin, and chilli; cook until golden.",
      "On low heat, sauté butter, garlic, onion, and tomato paste.",
      "Add milk, cream cheese, spinach, and chicken; simmer until creamy.",
      "Cook rice and divide with chicken among five containers.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 120, unit: "g", aisle: "protein" },
      { item: "Rice (uncooked)", qty: 40, unit: "g", aisle: "pantry" },
      { item: "Light butter", qty: 6, unit: "g", aisle: "dairy" },
      { item: "Ginger-garlic paste", qty: 0.2, unit: "tbsp", aisle: "pantry" },
      { item: "Onion", qty: 0.2, unit: "ea", aisle: "produce" },
      { item: "Tomato paste", qty: 0.2, unit: "tbsp", aisle: "pantry" },
      { item: "Skim milk", qty: 40, unit: "ml", aisle: "dairy" },
      { item: "Reduced-fat cream cheese", qty: 12, unit: "g", aisle: "dairy" },
      { item: "Spinach", qty: 0.4, unit: "cup", aisle: "produce" },
    ],
  },
  {
    id: "street-corn-chicken-bowls",
    name: "Street corn chicken bowls",
    slot: "dinner",
    diet: "omnivore",
    allergens: ["dairy", "egg"],
    calories: 544,
    protein: 50,
    carbs: 40,
    fat: 18,
    minutes: 40,
    note: "Macros per serving; batch serves 5. Mayonnaise allergen assumes standard egg-based mayo.",
    videoUrl: "https://www.instagram.com/reel/DLsVRFkqDuH/",
    steps: [
      "Marinate and pan-cook seasoned chicken until golden; finish with garlic and parsley.",
      "Mix corn, mayo, yogurt, hot sauce, jalapeño, cilantro, Tajín, lime, and feta.",
      "Cook basmati rice and fold in cilantro.",
      "Divide chicken and rice into bowls; keep corn salsa separate.",
    ],
    ingredients: [
      { item: "Chicken breast", qty: 200, unit: "g", aisle: "protein" },
      { item: "Sweet corn", qty: 80, unit: "g", aisle: "pantry" },
      { item: "Light mayo", qty: 12, unit: "g", aisle: "pantry" },
      { item: "Greek yogurt", qty: 20, unit: "g", aisle: "dairy" },
      { item: "Hot sauce", qty: 10, unit: "g", aisle: "pantry" },
      { item: "Jalapeño", qty: 10, unit: "g", aisle: "produce" },
      { item: "Feta cheese", qty: 20, unit: "g", aisle: "dairy" },
      { item: "Basmati rice (uncooked)", qty: 38, unit: "g", aisle: "pantry" },
      { item: "Cilantro", qty: 1, unit: "tbsp", aisle: "produce" },
      { item: "Lime", qty: 0.2, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "spinach-paneer",
    name: "High-protein spinach paneer",
    slot: "dinner",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 420,
    protein: 42,
    carbs: 22,
    fat: 14,
    minutes: 30,
    note: "Macros for the full recipe; caption does not state a serving count or side.",
    videoUrl: "https://www.instagram.com/reel/DYpRxM_Nok8/",
    steps: [
      "Sauté onion and ginger-garlic paste in oil.",
      "Add tomatoes and spices and cook until soft.",
      "Wilt spinach, then blend or chop to form a sauce.",
      "Add paneer and simmer until heated through; garnish with cilantro.",
    ],
    ingredients: [
      { item: "Low-fat paneer", qty: 200, unit: "g", aisle: "dairy" },
      { item: "Spinach", qty: 3, unit: "cup", aisle: "produce" },
      { item: "Onion", qty: 2, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 2, unit: "ea", aisle: "produce" },
      { item: "Ginger-garlic paste", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Olive oil", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Red chilli powder", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Coriander powder", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Cilantro", qty: 2, unit: "tbsp", aisle: "produce" },
    ],
  },
  {
    id: "palak-paneer-rice-meal",
    name: "Palak paneer rice meal",
    slot: "dinner",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 507,
    protein: 45,
    carbs: 51,
    fat: 13,
    minutes: 35,
    note: "Macros per meal.",
    videoUrl: "https://www.instagram.com/reel/DUko8aOCM4f/",
    steps: [
      "Air-fry paneer and sauté sweet corn.",
      "Sauté cumin, onion, ginger-garlic paste, tomato, and spices in oil.",
      "Blanch spinach and green chillies, blend, and simmer in the masala for 10 minutes.",
      "Serve palak sauce and paneer over rice with corn.",
    ],
    ingredients: [
      { item: "Cooked rice", qty: 150, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 150, unit: "g", aisle: "dairy" },
      { item: "Sweet corn", qty: 40, unit: "g", aisle: "frozen" },
      { item: "Spinach", qty: 1, unit: "bunch", aisle: "produce" },
      { item: "Green chillies", qty: 2, unit: "ea", aisle: "produce" },
      { item: "Olive oil", qty: 5, unit: "g", aisle: "pantry" },
      { item: "Onion", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Ginger-garlic paste", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "paneer-channa-masala",
    name: "Paneer channa masala",
    slot: "dinner",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 510,
    protein: 35,
    carbs: 62,
    fat: 15,
    minutes: 40,
    note: "Macros estimated per hearty serving (full-recipe caption totals halved).",
    videoUrl: "https://www.instagram.com/reel/DTaKv_LCB17/",
    steps: [
      "Marinate paneer with lemon, ginger-garlic paste, and spices, then pan-sear.",
      "Boil the channa until tender.",
      "Sauté onion, tomato, bell pepper, chilli, ginger-garlic paste, and spices.",
      "Fold in channa and paneer; finish with lemon and cilantro.",
    ],
    ingredients: [
      { item: "Paneer", qty: 200, unit: "g", aisle: "dairy" },
      { item: "Cooked chickpeas", qty: 150, unit: "g", aisle: "pantry" },
      { item: "Tomato", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Onion", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Bell pepper", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Green chillies", qty: 2, unit: "ea", aisle: "produce" },
      { item: "Ginger-garlic paste", qty: 2, unit: "tsp", aisle: "pantry" },
      { item: "Garam masala", qty: 2, unit: "tsp", aisle: "pantry" },
      { item: "Ghee", qty: 1, unit: "tsp", aisle: "dairy" },
      { item: "Lemon", qty: 0.5, unit: "ea", aisle: "produce" },
    ],
  },
  {
    id: "soya-kheema",
    name: "Soya kheema",
    slot: "dinner",
    diet: "vegan",
    allergens: ["soy"],
    calories: 230,
    protein: 20,
    carbs: 25,
    fat: 7,
    minutes: 35,
    note: "Macros per serving; batch makes 3.",
    videoUrl: "https://www.instagram.com/reel/C3-j-G-y7_g/",
    steps: [
      "Soak soy granules in salted hot water, then drain and squeeze dry.",
      "Sauté ginger-garlic paste, cumin, chilli, and onion until browned.",
      "Add tomato, carrot, tomato puree, and spices; cook down.",
      "Add soy granules, peas, soy sauce, and water; cover and simmer until thick.",
    ],
    ingredients: [
      { item: "Dry soya chunks", qty: 33.33, unit: "g", aisle: "pantry" },
      { item: "Olive oil", qty: 0.67, unit: "tsp", aisle: "pantry" },
      { item: "Ginger-garlic paste", qty: 0.33, unit: "tbsp", aisle: "pantry" },
      { item: "Onion", qty: 0.67, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.33, unit: "ea", aisle: "produce" },
      { item: "Carrot", qty: 0.08, unit: "cup", aisle: "produce" },
      { item: "Tomato paste", qty: 66.67, unit: "ml", aisle: "pantry" },
      { item: "Peas", qty: 0.17, unit: "cup", aisle: "frozen" },
      { item: "Soy sauce", qty: 0.67, unit: "tsp", aisle: "pantry" },
      { item: "Garam masala", qty: 0.33, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "hara-bhara-soya",
    name: "Hara bhara soya",
    slot: "dinner",
    diet: "vegetarian",
    allergens: ["dairy", "soy"],
    calories: 200,
    protein: 18,
    carbs: 16,
    fat: 8,
    minutes: 30,
    note: "Macros per serving; batch serves 2.",
    videoUrl: "https://www.instagram.com/reel/DbqIyathF2l/",
    steps: [
      "Marinate soya chunks with soy sauce, ginger-garlic paste, salt, and cornflour; pan-sear.",
      "Blend cilantro, green chillies, paneer, and water into a green paste.",
      "Sauté garlic and onion, then cook the green paste with spices.",
      "Add seared soya and simmer briefly.",
    ],
    ingredients: [
      { item: "Dry soya chunks (boiled)", qty: 50, unit: "g", aisle: "pantry" },
      { item: "Low-fat paneer", qty: 37.5, unit: "g", aisle: "dairy" },
      { item: "Cilantro", qty: 0.5, unit: "bunch", aisle: "produce" },
      { item: "Green chillies", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Onion", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Garlic", qty: 1.5, unit: "clove", aisle: "produce" },
      { item: "Ginger-garlic paste", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Cornflour", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Soy sauce", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Olive oil", qty: 1.25, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "lemon-garlic-soya",
    name: "Lemon garlic soya",
    slot: "dinner",
    diet: "vegetarian",
    allergens: ["dairy", "soy"],
    calories: 370,
    protein: 29,
    carbs: 39,
    fat: 13,
    minutes: 35,
    note: "Macros estimated per serving (full-recipe caption totals halved).",
    videoUrl: "https://www.instagram.com/reel/DazE7k9z4at/",
    steps: [
      "Boil soya chunks with salt, sugar, and ginger-garlic paste; squeeze dry.",
      "Coat with cornflour, spices, and ghee, then pan-fry or air-fry until crisp.",
      "Cook garlic and green chilli in ghee and butter; add cornflour, water, and lemon.",
      "Simmer until thick, then toss in crispy soya.",
    ],
    ingredients: [
      { item: "Dry soya chunks", qty: 100, unit: "g", aisle: "pantry" },
      { item: "Ginger-garlic paste", qty: 0.5, unit: "tbsp", aisle: "pantry" },
      { item: "Cornflour", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Ghee", qty: 2.5, unit: "tsp", aisle: "dairy" },
      { item: "Butter", qty: 2, unit: "tsp", aisle: "dairy" },
      { item: "Garlic", qty: 10, unit: "clove", aisle: "produce" },
      { item: "Green chilli", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Lemon", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Coriander powder", qty: 1, unit: "tbsp", aisle: "pantry" },
    ],
  },

  // ---------- snack ----------
  {
    id: "paneer-pockets",
    name: "High-protein paneer pockets",
    slot: "snack",
    diet: "vegetarian",
    allergens: ["dairy", "gluten"],
    calories: 200,
    protein: 14,
    carbs: 27,
    fat: 5,
    minutes: 30,
    note: "Macros per pocket; batch makes 4.",
    videoUrl: "https://www.instagram.com/reel/DQhF93sDR7s/",
    steps: [
      "Sauté onion, tomato, and bell pepper with spices.",
      "Fold in crumbled paneer and cilantro.",
      "Fill four rotis, seal into pockets, and air-fry or toast until crisp.",
    ],
    ingredients: [
      { item: "Low-fat paneer", qty: 50, unit: "g", aisle: "dairy" },
      { item: "Chapati", qty: 1, unit: "ea", aisle: "bakery" },
      { item: "Onion", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Tomato", qty: 0.5, unit: "ea", aisle: "produce" },
      { item: "Bell pepper", qty: 0.25, unit: "ea", aisle: "produce" },
      { item: "Olive oil", qty: 0.25, unit: "tsp", aisle: "pantry" },
      { item: "Cilantro", qty: 0.5, unit: "tbsp", aisle: "produce" },
      { item: "Red chilli powder", qty: 0.25, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "crispy-parmesan-chickpeas",
    name: "Crispy parmesan chickpeas",
    slot: "snack",
    diet: "vegetarian",
    allergens: ["dairy"],
    calories: 316,
    protein: 19,
    carbs: 52,
    fat: 7,
    minutes: 20,
    note: "Macros for the caption's full snack portion.",
    videoUrl: "https://www.instagram.com/reel/DGwx53MxUou/",
    steps: [
      "Drain, rinse, and thoroughly dry the chickpeas.",
      "Coat with cooking spray, parmesan, paprika, cumin, salt, and pepper.",
      "Air-fry at 390°F for 15 minutes, shaking once.",
    ],
    ingredients: [
      { item: "Cooked chickpeas", qty: 344, unit: "g", aisle: "pantry" },
      { item: "Parmesan", qty: 1, unit: "tbsp", aisle: "dairy" },
      { item: "Paprika", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Cumin powder", qty: 0.5, unit: "tsp", aisle: "pantry" },
      { item: "Olive oil", qty: 1, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "crispy-chicken-nuggets",
    name: "Air-fryer crispy chicken nuggets",
    slot: "snack",
    diet: "omnivore",
    allergens: ["egg", "dairy"],
    calories: 250,
    protein: 30,
    carbs: 8,
    fat: 10,
    minutes: 30,
    note: "Snack portion ~8 nuggets with garlic yogurt dip. Full plate is 30 nuggets / 948 kcal.",
    videoUrl: "https://www.instagram.com/reel/DbTPgfiNJ6X/",
    steps: [
      "Mix chicken, egg, mozzarella, and seasonings.",
      "Shape 30 nuggets and wrap each with rice-paper pieces.",
      "Air-fry at 200°C for 15–20 minutes, shaking halfway.",
      "Stir yogurt, mayo, garlic, and salt for the dip.",
    ],
    ingredients: [
      { item: "Lean ground chicken", qty: 133.33, unit: "g", aisle: "protein" },
      { item: "Egg", qty: 0.27, unit: "ea", aisle: "protein" },
      { item: "Mozzarella", qty: 0.07, unit: "cup", aisle: "dairy" },
      { item: "Rice paper sheets", qty: 1.33, unit: "ea", aisle: "pantry" },
      { item: "Greek yogurt", qty: 26.67, unit: "g", aisle: "dairy" },
      { item: "Light mayo", qty: 8, unit: "g", aisle: "pantry" },
      { item: "Ginger-garlic paste", qty: 0.13, unit: "tsp", aisle: "pantry" },
      { item: "Smoked paprika", qty: 0.27, unit: "tsp", aisle: "pantry" },
    ],
  },
  {
    id: "makhana-sprout-chaat",
    name: "Makhana sprout chaat",
    slot: "snack",
    diet: "vegan",
    allergens: ["nuts"],
    calories: 220,
    protein: 10,
    carbs: 28,
    fat: 8,
    minutes: 25,
    note: "Approximate macros per serving.",
    videoUrl: "https://www.instagram.com/reel/DWlHGy0Av5b/",
    steps: [
      "Dry-roast makhana until crisp.",
      "Blend soaked red chillies and garlic, then cook the paste until thick.",
      "Toss makhana with sprouts, onion, peanuts, cilantro, chaat masala, and chilli-garlic paste.",
    ],
    ingredients: [
      { item: "Makhana (fox nuts)", qty: 1, unit: "cup", aisle: "pantry" },
      { item: "Sprouts", qty: 1, unit: "cup", aisle: "produce" },
      { item: "Onion", qty: 1, unit: "ea", aisle: "produce" },
      { item: "Peanuts", qty: 2, unit: "tbsp", aisle: "pantry" },
      { item: "Dried red chillies", qty: 8, unit: "ea", aisle: "pantry" },
      { item: "Garlic", qty: 5, unit: "clove", aisle: "produce" },
      { item: "Chaat masala", qty: 1, unit: "tsp", aisle: "pantry" },
      { item: "Cilantro", qty: 2, unit: "tbsp", aisle: "produce" },
    ],
  },

];
