/** WorkoutX name-search terms keyed by BlueHour exercise id. */
export const WORKOUTX_QUERY: Record<string, string> = {
  "warm-hip-flow": "worlds greatest stretch",
  "warm-glute-bridge": "glute bridge",
  "warm-ankle-rock": "ankle dorsiflexion",
  "sq-goblet": "goblet squat",
  "hi-hip-hinge": "dumbbell romanian deadlift",
  "sl-step-up": "step up",
  "pu-pushup": "push up",
  "pl-row": "dumbbell row",
  "ca-calf-raise": "standing calf raise",
  "sq-front-squat": "dumbbell front squat",
  "hi-single-rdl": "single leg romanian deadlift",
  "sl-split-squat": "bulgarian split squat",
  "pu-incline-press": "incline dumbbell press",
  "pl-pulldown": "lat pulldown",
  "cr-suitcase-carry": "suitcase carry",
  "sq-back-squat": "barbell squat",
  "hi-trap-deadlift": "trap bar deadlift",
  "sl-walking-lunge": "walking lunge",
  "pu-overhead-press": "overhead press",
  "pl-pullup": "pull up",
  "ca-eccentric-calf": "single leg calf raise",
  "core-dead-bug": "dead bug",
  "core-plank": "plank",
  "core-side-plank": "side plank",
  "core-bird-dog": "bird dog",
  "core-dead-bug-reach": "dead bug",
  "core-hollow-hold": "hollow hold",
  "core-shoulder-taps": "plank shoulder tap",
  "core-pallof": "pallof press",
  "core-reverse-crunch": "reverse crunch",
  "core-hanging-knee": "hanging knee raise",
  "core-hollow-rock": "hollow rock",
  "core-ab-wheel-half": "ab wheel",
  "core-copenhagen": "copenhagen",
  "core-cable-crunch": "cable crunch",
  "core-hanging-leg": "hanging leg raise",
  "core-ab-wheel-full": "ab wheel",
  "core-dragon-negative": "dragon flag",
  "core-weighted-side-plank": "side plank",
  "core-cable-crunch-heavy": "cable crunch",
  "mob-hip-flow": "hip stretch",
  "mob-calf-wall": "calf stretch",
  "mob-dead-bug": "dead bug",
  "sl-glute-bridge": "single leg glute bridge",
  "core-side-plank-a": "side plank",
  "core-side-plank-a2": "side plank hip dip",
  "core-side-plank-a3": "side plank",
  "hi-single-rdl-b": "single leg romanian deadlift",
  "lat-band-walk": "lateral band walk",
  "lat-band-walk-2": "lateral band walk",
  "core-dead-bug-b": "dead bug",
  "cr-farmer-b": "farmers walk",
  "cr-farmer-b3": "suitcase carry",
  "abs-b-side": "side plank",
  "abs-b-heel": "heel touch crunch",
  "abs-b-squeeze": "adductor squeeze",
  "abs-b-carry": "suitcase carry",
};
